#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import sum_args


def get_after_tax_income_column(predepreciation_income_column, total_taxes_column):
    """Get the after tax income column (Column Y)"""
    return list(
        map(
            lambda predepreciation_income, total_taxes: sum_args(
                predepreciation_income, total_taxes
            ),
            predepreciation_income_column,
            total_taxes_column,
        )
    )
