#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import TRUE


def determine_operation_year(i, construct):
    """Helper function in generating the list of operation years"""
    if i == construct:
        return 1
    elif i < construct:
        return -construct + i
    elif TRUE:
        return i - construct + 1


def get_operation_range(analysis_year_num_range, construct):
    """Get the range of plant operation years"""
    return list(
        map(lambda i: determine_operation_year(i, construct), analysis_year_num_range)
    )


def determine_inflation_price_increase_factor(year, inflation_rate, startup_year):
    """Helper function in generating the list of inflation price increase factors"""
    return (1 + inflation_rate) ** (year - startup_year)


def get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year):
    """Get the inflation price increase factors over the analysis range"""
    return list(
        map(
            lambda year: determine_inflation_price_increase_factor(
                year, inflation_rate, startup_year
            ),
            analysis_range,
        )
    )
