#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import YEAR_1, slice, sum_args


def get_aftertax_post_depreciation_cashflow(
    initial_equity_depr_cap,
    replacement_costs,
    working_cap_reserve_column,
    other_non_depreciable_capital_cost_column,
    predepreciation_income_column,
    total_taxes_column,
    principal_payments_column,
):
    """Calculates the After-Tax Post-Depreciation Cash Flow"""
    return list(
        map(
            lambda depr_cap, replacement_costs, working_cap_reserve, other_non_depreciable_capital_cost, predepreciation_income, total_taxes, principal_payments: sum_args(
                depr_cap,
                replacement_costs,
                working_cap_reserve,
                other_non_depreciable_capital_cost,
                predepreciation_income,
                total_taxes,
                principal_payments,
            ),
            initial_equity_depr_cap,
            replacement_costs,
            working_cap_reserve_column,
            other_non_depreciable_capital_cost_column,
            predepreciation_income_column,
            total_taxes_column,
            principal_payments_column,
        )
    )


def get_cumulative_cashflow_column(cashflow_column, analysis_index_range):
    """Calculates the Cumulative Cash Flow Column"""
    return list(
        map(lambda i: sum(slice(cashflow_column, YEAR_1, i + 1)), analysis_index_range)
    )


def get_pretax_cashflow_column(
    initial_equity_depr_cap,
    replacement_costs,
    working_cap_reserve_column,
    other_non_depreciable_capital_cost_column,
    predepreciation_income_column,
    principal_payments_column,
):
    """Calculates the Pre-Tax Cash Flow"""
    return list(
        map(
            lambda depr_cap, replacement_costs, working_cap_reserve, other_non_depreciable_capital_cost, predepreciation_income, principal_payments: sum_args(
                depr_cap,
                replacement_costs,
                working_cap_reserve,
                other_non_depreciable_capital_cost,
                predepreciation_income,
                principal_payments,
            ),
            initial_equity_depr_cap,
            replacement_costs,
            working_cap_reserve_column,
            other_non_depreciable_capital_cost_column,
            predepreciation_income_column,
            principal_payments_column,
        )
    )
