#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import get
from h2a.ref_tables import macrs_depreciation_table


def calculate_depreciation(
    op_year, depreciable_capital, recovery_year, depr_type, depr_length
):
    """Calculate the depreciation for a given recovery year and operation year"""
    if depr_type == "Straight Line" and recovery_year <= depr_length:
        return depreciable_capital / depr_length
    elif depr_type == "MACRS" and recovery_year <= depr_length + 1:
        return (
            depreciable_capital
            * get(get(macrs_depreciation_table, depr_length), recovery_year)
            / 100
        )
    else:
        return 0


def calculate_depreciation_column(
    recovery_year, operation_range, depr_type, depr_length, annual_depreciable_capital
):
    """Calculate the depreciation for a given recovery year and operation range"""
    return list(
        map(
            lambda op_year, depreciable_capital: calculate_depreciation(
                op_year, depreciable_capital, recovery_year, depr_type, depr_length
            ),
            operation_range,
            annual_depreciable_capital,
        )
    )


def get_depreciation_calculation_table(
    recovery_range, operation_range, depr_type, depr_length, annual_depreciable_capital
):
    """Get the 2D table of depreciation calculations (recovery_range by operation_range)"""
    return list(
        map(
            lambda recovery_year: calculate_depreciation_column(
                recovery_year,
                operation_range,
                depr_type,
                depr_length,
                annual_depreciable_capital,
            ),
            recovery_range,
        )
    )
