#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.globals import CEPCIinflator, CPIinflator


def site_preparation():
    return 0.159872128446844 * direct_cap / (CEPCIinflator * CPIinflator)
