#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import TRUE


def calculate_h2_sales_kg_per_year(
    year, plant_output_kg_per_year, percnt_revs, start_time
):
    if year < 0:
        return 0
    elif year == 1 and start_time < 1:
        return (plant_output_kg_per_year * percnt_revs * start_time) + (
            plant_output_kg_per_year * (1 - start_time)
        )
    elif year <= start_time:
        return plant_output_kg_per_year * percnt_revs
    else:
        return plant_output_kg_per_year


def get_h2_sales_kg_per_year(
    operation_range, plant_output_kg_per_year, percnt_revs, start_time
):
    """H2 sales (kg/year)"""
    return list(
        map(
            lambda year: calculate_h2_sales_kg_per_year(
                year, plant_output_kg_per_year, percnt_revs, start_time
            ),
            operation_range,
        )
    )
