#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import get
from h2a.ref_tables import chemical_price_index, non_energy_material_prices


def get_nonenergy_material_price_conversion_factor(nonenergy_material, ref_year):
    """Get the conversion factor for converting Non-Energy Material prices from source year to reference year dollars"""
    return get(chemical_price_index, ref_year) / get(
        chemical_price_index,
        get(
            get(non_energy_material_prices, "Source Data Year"),
            get(nonenergy_material, "name"),
        ),
    )


def get_nonenergy_material_price_for_year(
    year, nonenergy_material, INFLATION_FACTOR, ref_year
):
    """Calculate the price of a given Non-Energy Material for a year (although year is not used in this function)"""
    return (
        INFLATION_FACTOR
        * get(nonenergy_material, "usage")
        * (
            get(
                get(non_energy_material_prices, "Price"),
                get(nonenergy_material, "name"),
            )
            * get_nonenergy_material_price_conversion_factor(
                nonenergy_material, ref_year
            )
        )
    )


def prices_for_nonenergy_material(
    nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year
):
    """Get prices for a given Non-Energy Material over a range of years"""
    return list(
        map(
            lambda year: get_nonenergy_material_price_for_year(
                year, nonenergy_material, INFLATION_FACTOR, ref_year
            ),
            analysis_range,
        )
    )


def get_nonenergy_material_price_df(
    nonenergy_materials, analysis_range, INFLATION_FACTOR, ref_year
):
    """Get a dataframe of Non-Energy Material prices over a range of years"""
    return list(
        map(
            lambda nonenergy_material: prices_for_nonenergy_material(
                nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year
            ),
            nonenergy_materials,
        )
    )
