#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import TRUE, YEAR_1


def calculate_other_non_depr_cap(year, inflation_price_increase_factor, non_dep_infl):
    if year == YEAR_1:
        return -inflation_price_increase_factor * non_dep_infl
    else:
        return 0


def get_other_non_depreciable_capital_cost_column(
    analysis_index_range, inflation_price_increase_factors, non_dep_infl
):
    """Other Non-Depreciable Capital Costs"""
    return list(
        map(
            lambda year, inflation_price_increase_factor: calculate_other_non_depr_cap(
                year, inflation_price_increase_factor, non_dep_infl
            ),
            analysis_index_range,
            inflation_price_increase_factors,
        )
    )
