#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import round_num


def convert_to_metric_tons_per_year(emission, plant_output_kg_per_year):
    """Converts a value in kg per kg H2 to metric tons per year"""
    return round_num(emission * plant_output_kg_per_year / 1000, -2)


def get_total_in_metric_tons_per_year(
    total_process_pollutants_produced_kg_per_kg_h2, plant_output_kg_per_year
):
    """Convert total emissions for each GHG to metric tons per year"""
    return list(
        map(
            lambda emission: convert_to_metric_tons_per_year(
                emission, plant_output_kg_per_year
            ),
            total_process_pollutants_produced_kg_per_kg_h2,
        )
    )
