#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import evaluate, get, to_str


def calculate_replacement_cost(
    year,
    inflation_price_increase_factor,
    replacement_costs_for_years,
    replace_factor,
    depr_cap,
    ref_year,
    startup_year,
    inflation_rate,
):
    if year < 0:
        return 0
    else:
        return (
            -inflation_price_increase_factor
            * (
                evaluate(to_str(get(replacement_costs_for_years, year, 0)))
                + (replace_factor * depr_cap)
            )
            * ((1 + inflation_rate) ** (startup_year - ref_year))
        )


def get_replacement_costs(
    operation_range,
    inflation_price_increase_factors,
    replacement_costs_for_years,
    replace_factor,
    depr_cap,
    ref_year,
    startup_year,
    inflation_rate,
):
    """Unplanned Yearly Replacement Capital (Depreciable)"""
    return list(
        map(
            lambda year, inflation_price_increase_factor: calculate_replacement_cost(
                year,
                inflation_price_increase_factor,
                replacement_costs_for_years,
                replace_factor,
                depr_cap,
                ref_year,
                startup_year,
                inflation_rate,
            ),
            operation_range,
            inflation_price_increase_factors,
        )
    )
