#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.helpers import sum_args


def get_taxable_income_column(
    predepreciation_income_column, depreciation_charges_column
):
    """Get the Taxable Income (Column V)"""
    return list(
        map(
            lambda predepreciation_income, depreciation_charges: sum_args(
                predepreciation_income, depreciation_charges
            ),
            predepreciation_income_column,
            depreciation_charges_column,
        )
    )
