#
# This file is programmatically generated by py_writer.py; do not edit
#
def calculate_total_taxes(
    taxable_income, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear
):
    """Calculate the total taxes for a given taxable income"""
    return tax_credit - (
        taxable_income * total_tax_rate + Upstream_CO2_taxpYear + Proc_CO2_taxpYear
    )


def get_total_taxes_column(
    taxable_income_column,
    total_tax_rate,
    tax_credit,
    Upstream_CO2_taxpYear,
    Proc_CO2_taxpYear,
):
    """Get the total taxes column (Column X)"""
    return list(
        map(
            lambda taxable_income: calculate_total_taxes(
                taxable_income,
                total_tax_rate,
                tax_credit,
                Upstream_CO2_taxpYear,
                Proc_CO2_taxpYear,
            ),
            taxable_income_column,
        )
    )
