#
# This file is programmatically generated by py_writer.py; do not edit
#
from h2a.ref_tables import *
from h2a.inputs import *
from h2a.globals import *
from h2a.lib.cashflow_meta import *
from h2a.lib.other_materials import *
from h2a.lib.feedstock_costs import *
from h2a.lib.feedstock_prices import *
from h2a.lib.capital_investments import *
from h2a.lib.functions import *

H2_LHV_MJ_p_kg = get_lhv("Hydrogen")
output_energy_MMBtu_per_year = plant_output_kg_per_year * H2_LHV_MJ_p_kg / 1000 / conversion_factor("mmBTU_to_GJ")
output_energy_MJ_per_year = plant_output_kg_per_year * H2_LHV_MJ_p_kg
nominal_irr = ((1 + real_irr) * (1 + inflation_rate)) - 1
percentage_debt_financing = 1 - percentage_equity_financing
target_after_tax_nominal_irr = (1 + real_irr)*(1 + inflation_rate) - 1
analysis_range = range(analysis_period_start, analysis_period_end)
feedstock_price_df = get_feedstock_price_df(feedstocks, analysis_range)
operation_range = get_operation_range(seq_along(analysis_range), construct)
inflation_price_increase_factors = get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year)
total_feedstock_cost_column = get_total_feedstock_costs(operation_range, feedstock_price_df, inflation_price_increase_factors, start_time, plant_output_kg_per_year, percnt_var)
other_material_price_df = get_other_material_price_df(other_materials, analysis_range, INFLATION_FACTOR, ref_year)
direct_cap = capital_investment_costs(capital_investments)
# = =(total_cap - non_dep_cap) * INFLATION_FACTOR
