#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(get, to_num, .from = "helpers.R", .directory = here("h2a"))
calculate_capital_investment_cost <- function(capital_investment, CEPCIinflator, CPIinflator) {
    return(to_num(get(capital_investment, 'cost')) * CEPCIinflator * CPIinflator * to_num(get(capital_investment, 'installation_cost_factor')))
}
capital_investment_costs <- function(capital_investments, CEPCIinflator, CPIinflator) {
    #'H2A Total Direct Capital Cost
    return(mapply(function(capital_investment) list(calculate_capital_investment_cost(capital_investment, CEPCIinflator, CPIinflator)), capital_investments) )
}
