#
# This file is programmatically generated by py_writer.py; do not edit
#

get_cc_transport_cost <- function(CO2_Capture_Efficiency, co2_mass_flowrate_million_metric_tonnes_per_year, capacity_factor, pipeline_length_km) {
    #'Get the cost of transporting CO2 via pipeline
    if (CO2_Capture_Efficiency > 0) {
        return((0.00129370797716017 + 0.0687815698196632 * co2_mass_flowrate_million_metric_tonnes_per_year ** (-1) * (1 / capacity_factor) ** (-0.0166514964188321) + 0.01731727171502 * co2_mass_flowrate_million_metric_tonnes_per_year ** (-0.156118324462401) * (1 / capacity_factor) ** (0.824934911964665) + (-0.000137394421827598) * co2_mass_flowrate_million_metric_tonnes_per_year ** (0.470662342349608) * (1 / capacity_factor) ** (1.75242487142674)) * pipeline_length_km / 1.609)
    }
    else {
        return(0)
    }
}
get_cc_storage_cost <- function(CO2_Capture_Efficiency, co2_mass_flowrate_million_metric_tonnes_per_year, capacity_factor) {
    #'Get the cost of storing CO2 in a saline aquifer
    if (CO2_Capture_Efficiency > 0) {
        return((64.3091554851963 + (-60.1502370649192) * co2_mass_flowrate_million_metric_tonnes_per_year ** 0.0712303362822559 * (1/capacity_factor) ** (-0.000226851495312583) + (-0.116800620833705) * co2_mass_flowrate_million_metric_tonnes_per_year ** 0 * (1/capacity_factor) ** 1.92441118127662 + 0.410829252323417 * co2_mass_flowrate_million_metric_tonnes_per_year ** 0.044749413871132 * (1/capacity_factor) ** 1.54290340943809 + 6.21719206349344 * co2_mass_flowrate_million_metric_tonnes_per_year ** 0.407088119558414 * (1/capacity_factor) ** (0) + 8.56835238443595 * co2_mass_flowrate_million_metric_tonnes_per_year ** (-0.935407651008645) * (1/capacity_factor) ** (-0.0439391293507022) + 1.04841400308413 * co2_mass_flowrate_million_metric_tonnes_per_year ** (-1.45658112848623) * (1/capacity_factor) ** (0.0518742090550712)))
    }
    else {
        return(0)
    }
}
