#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(YEAR_1, .from = "helpers.R", .directory = here("h2a"))
calculate_principal_payment_when_constant_debt <- function(year, last_year, initial_capital_financed) {
    #'✅ Annual payment for the constant debt case
    if (year == last_year) {
        return(initial_capital_financed)
    }
    else {
        return(0)
    }
}
calculate_principal_payment_when_paying_debt <- function(annual_payment, interest_amount) {
    #'📝 Annual payment for when making payments that decrease the balance
    if (BALANCE_EXISTS) {
        return(annual_payment - interest_amount)
    }
    else {
        return(0)
    }
}
get_principal_payments_constant_debt <- function(analysis_range, last_year, initial_capital_financed) {
    #'Principal payments for the constant debt case
    return(mapply(function(year) list(calculate_principal_payment_when_constant_debt(year, last_year, initial_capital_financed)), analysis_range) )
}
determine_principal_payment <- function(debt_period, analysis_range, last_year, initial_capital_financed) {
    #'✅ Constant or paying down debt?
    if (debt_period == 0) {
        return(get_principal_payments_constant_debt(analysis_range, last_year, initial_capital_financed))
    }
    else {
        return(calculate_principal_payment_when_paying_debt)
    }
}
calculate_interest_amount <- function(year, balance, debt_interest) {
    #'📝 Interest amount for the current year
    return(balance * debt_interest)
}
get_interest_payments_constant_debt <- function(analysis_range, initial_capital_financed, debt_interest) {
    #'Interest payments for the constant debt case
    return(mapply(function(year) list(calculate_interest_amount(year, initial_capital_financed, debt_interest)), analysis_range) )
}
determine_interest_payment <- function(debt_period, analysis_range, initial_capital_financed, debt_interest) {
    #'✅ Constant or paying down debt?
    if (debt_period == 0) {
        return(get_interest_payments_constant_debt(analysis_range, initial_capital_financed, debt_interest))
    }
    else {
        return(calculate_principal_payment_when_paying_debt)
    }
}
determine_annual_payment <- function(debt_period, initial_capital_financed, debt_interest) {
    if (debt_period == 0) {
        return(initial_capital_financed * debt_interest)
    }
    else {
        return(previous_value)
    }
}
calculate_principal_owed <- function(year) {
    if (year == YEAR_1) {
        return(initial_capital_financed)
    }
    else {
        return(previous_value - principal_paid)
    }
}
