#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(FIRST, .from = "helpers.R", .directory = here("h2a"))
calculate_decom_cost <- function(year, inflation_price_increase_factor, decom, plant_life) {
    if (year == plant_life + FIRST) {
        return(-inflation_price_increase_factor * decom)
    }
    else {
        return(0)
    }
}
get_decom_costs_column <- function(operation_range, inflation_price_increase_factors, decom, plant_life) {
    #'Decommissioning Costs column
    return(mapply(function(year, inflation_price_increase_factor) list(calculate_decom_cost(year, inflation_price_increase_factor, decom, plant_life)), operation_range, inflation_price_increase_factors) )
}
