#
# This file is programmatically generated by py_writer.py; do not edit
#

import::here(get_macrs, .from = "ref_tables.R", .directory = here("h2a"))
calculate_depreciation <- function(op_year, depreciable_capital, recovery_year, depr_type, depr_length) {
    #'Calculate the depreciation for a given recovery year and operation year
    if (depr_type == 'Straight Line' && recovery_year <= depr_length) {
        return(depreciable_capital / depr_length)
    }
    else if (depr_type == 'MACRS' && recovery_year <= depr_length + 1) {
        return(depreciable_capital * get_macrs(recovery_year, depr_length))
    }
    else {
        return(0)
    }
}
calculate_depreciation_column <- function(recovery_year, operation_range, depr_type, depr_length, annual_depreciable_capital) {
    #'Calculate the depreciation for a given recovery year and operation range
    return(mapply(function(op_year, depreciable_capital) list(calculate_depreciation(op_year, depreciable_capital, recovery_year, depr_type, depr_length)), operation_range, annual_depreciable_capital) )
}
get_depreciation_calculation_table <- function(recovery_range, operation_range, depr_type, depr_length, annual_depreciable_capital) {
    #'Get the 2D table of depreciation calculations (recovery_range by operation_range)
    return(mapply(function(recovery_year) list(calculate_depreciation_column(recovery_year, operation_range, depr_type, depr_length, annual_depreciable_capital)), recovery_range) )
}
