#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", get, .directory = here(h2a))
import::from("ref_tables.R", macrs_depreciation_table, .directory = here(h2a))
calculate_depreciation <- function(op_year, depreciable_capital, recovery_year, depr_type, depr_length) {
    #'Calculate the depreciation for a given recovery year and operation year
    if (depr_type == 'Straight Line' && recovery_year <= depr_length) {
        return(depreciable_capital / depr_length)
    }
    else if (depr_type == 'MACRS' && recovery_year <= depr_length + 1) {
        return(depreciable_capital * get(get(macrs_depreciation_table, depr_length), recovery_year))
    }
    else {
        return(0)
    }
}
calculate_depreciation_column <- function(recovery_year, operation_range, depr_type, depr_length, annual_depreciable_capital) {
    #'Calculate the depreciation for a given recovery year and operation range
    return(lapply(operation_range, annual_depreciable_capital, function(op_year, depreciable_capital) calculate_depreciation(op_year, depreciable_capital, recovery_year, depr_type, depr_length)))
}
get_depreciation_calculation_table <- function(recovery_range, operation_range, depr_type, depr_length, annual_depreciable_capital) {
    #'Get the 2D table of depreciation calculations (recovery_range by operation_range)
    return(lapply(recovery_range, function(recovery_year) calculate_depreciation_column(recovery_year, operation_range, depr_type, depr_length, annual_depreciable_capital)))
}
