#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(FIRST, concat, get, get_cell, split, to_num, .from = "helpers.R", .directory = here("h2a"))
import::here(conversion_factor, upstream_energy_and_emissions, .from = "ref_tables.R", .directory = here("h2a"))
calculate_energy_input_for_feedstock <- function(feedstock) {
    #'Get the energy input value for a feedstock
    return(to_num(get(feedstock, 'usage')) * conversion_factor(concat(get(split(get(feedstock, 'units'),'/'), FIRST), '_to_$/GJ')))
}
get_energy_input_for_feedstocks <- function(feedstocks) {
    #'Get a dataframe of the energy input value for each feedstock
    return(mapply(function(feedstock) list(calculate_energy_input_for_feedstock(feedstock)), feedstocks) )
}
calculate_upstream_energy_usage_for_feedstock_and_energy_column <- function(column_name, feedstock, energy_input) {
    #'Get the upstream energy usage for a feedstock
    return(energy_input / 1000000 * get_cell(upstream_energy_and_emissions, get(feedstock, 'name'), column_name))
}
iterate_over_energy_columns_for_feedstock <- function(feedstock, energy_input, upstream_energy_usage_column_names) {
    #'Iterate over the energy columns for a feedstock
    return(mapply(function(column_name) list(calculate_upstream_energy_usage_for_feedstock_and_energy_column(column_name, feedstock, energy_input)), upstream_energy_usage_column_names) )
}
get_upstream_energy_usage_for_feedstocks <- function(feedstocks, energy_input_GJ_per_kg_h2, upstream_energy_usage_column_names) {
    #'Get the upstream energy usage for the feedstocks
    return(mapply(function(feedstock, energy_input) list(iterate_over_energy_columns_for_feedstock(feedstock, energy_input, upstream_energy_usage_column_names)), feedstocks, energy_input_GJ_per_kg_h2) )
}
