#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", concat, get, split, .directory = here(h2a))
import::from("ref_tables.R", conversion_factor, upstream_energy_and_emissions, .directory = here(h2a))
calculate_energy_input_for_feedstock <- function(feedstock) {
    #'Get the energy input value for a feedstock
    return(get(feedstock, 'usage') * conversion_factor(concat(get(split(get(feedstock, 'units'),'/'), 0), '_to_$/GJ')))
}
get_energy_input_for_feedstocks <- function(feedstocks) {
    #'Get a dataframe of the energy input value for each feedstock
    return(lapply(feedstocks, function(feedstock) calculate_energy_input_for_feedstock(feedstock)))
}
calculate_upstream_energy_usage_for_feedstock_and_energy_column <- function(column_name, feedstock, energy_input) {
    #'Get the upstream energy usage for a feedstock
    return(energy_input / 1000000 * get(get(upstream_energy_and_emissions, column_name), get(feedstock, 'name')))
}
iterate_over_energy_columns_for_feedstock <- function(feedstock, energy_input, upstream_energy_usage_column_names) {
    #'Iterate over the energy columns for a feedstock
    return(lapply(upstream_energy_usage_column_names, function(column_name) calculate_upstream_energy_usage_for_feedstock_and_energy_column(column_name, feedstock, energy_input)))
}
get_upstream_energy_usage_for_feedstocks <- function(feedstocks, energy_input_GJ_per_kg_h2, upstream_energy_usage_column_names) {
    #'Get the upstream energy usage for the feedstocks
    return(lapply(feedstocks, energy_input_GJ_per_kg_h2, function(feedstock, energy_input) iterate_over_energy_columns_for_feedstock(feedstock, energy_input, upstream_energy_usage_column_names)))
}
