#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("globals.R", INFLATION_FACTOR, .directory = here(h2a))
import::from("helpers.R", get, split, concat, .directory = here(h2a))
import::from("ref_tables.R", conversion_factor, get_aeo, .directory = here(h2a))
get_feedstock_price_for_year <- function(year, feedstock) {
    #'Get the price of a feedstock for a given year
    return(
        get(
            get(
                get_aeo(get(feedstock, "price_table")),
                get(feedstock, "name")
            ),
            year
        ) *
            get(feedstock, "usage") *
            conversion_factor(
                concat(
                  get(
                    split(
                      get(feedstock, "units"),
                      "/"
                  ),
                    0
                ),
                  "_to_$/GJ"
              )
            ) *
            INFLATION_FACTOR
    )
}
lookup_prices_for_feedstock <- function(analysis_range, feedstock) {
    #'Lookup prices for a given feedstock over a range of years
    return(
        lapply(analysis_range, function(year) get_feedstock_price_for_year(year, feedstock))
    )
}
get_feedstock_price_for_startup_year <- function(year, feedstock, startup_year) {
    #'Get the price of a feedstock for the startup year
    return(
        get(
            get(
                get_aeo(get(feedstock, "price_table")),
                get(feedstock, "name")
            ),
            startup_year
        ) *
            get(feedstock, "usage") *
            conversion_factor(
                concat(
                  get(
                    split(
                      get(feedstock, "units"),
                      "/"
                  ),
                    0
                ),
                  "_to_$/GJ"
              )
            ) *
            INFLATION_FACTOR
    )
}
fixed_prices_for_feedstock <- function(analysis_range, feedstock, startup_year) {
    #'Get fixed prices for a given feedstock over a range of years
    return(
        lapply(
            analysis_range, function(year) get_feedstock_price_for_startup_year(year, feedstock, startup_year)
        )
    )
}
select_feedstock_prices <- function(feedstock, analysis_range, startup_year) {
    #'For a given feedstock, select whether to lookup prices or use a fixed price
    if (get(feedstock, "lookup_prices")) {
        return(lookup_prices_for_feedstock(analysis_range, feedstock))
    } else {
        return(fixed_prices_for_feedstock(analysis_range, feedstock, startup_year))
    }
}
get_feedstock_price_df <- function(feedstocks, analysis_range, startup_year) {
    #'Get a dataframe of prices by feedstock and year
    return(
        lapply(
            feedstocks, function(feedstock) select_feedstock_prices(feedstock, analysis_range, startup_year)
        )
    )
}
