#
# This file is programmatically generated by py_writer.py; do not edit
#
calculate_fixed_cost <- function(year, inflation_price_increase_factor, inflated_fixed, percnt_fixed, start_time) {
    if (year < 0) {
        return(0)
    }
    else if (year == 1 && start_time < 1) {
        return(-(( inflated_fixed * percnt_fixed * start_time) + ( inflated_fixed * (1 - start_time) )))
    }
    else if (year <= start_time) {
        return(-(inflated_fixed * percnt_fixed * inflation_price_increase_factor))
    }
    else {
        return(-(inflated_fixed * inflation_price_increase_factor))
    }
}
get_fixed_cost_column <- function(operation_range, inflation_price_increase_factors, inflated_fixed, percnt_fixed, start_time) {
    #'Fixed Operating Costs column
    return(lapply(operation_range, inflation_price_increase_factors, function(year, inflation_price_increase_factor) calculate_fixed_cost(year, inflation_price_increase_factor, inflated_fixed, percnt_fixed, start_time)))
}
