#
# This file is programmatically generated by py_writer.py; do not edit
#

calculate_h2_sales_kg_per_year <- function(year, plant_output_kg_per_year, percnt_revs, start_time) {
    if (year < 0) {
        return(0)
    }
    else if (year == 1 && start_time < 1) {
        return(( plant_output_kg_per_year * percnt_revs * start_time) + ( plant_output_kg_per_year * (1 - start_time) ))
    }
    else if (year <= start_time) {
        return(plant_output_kg_per_year * percnt_revs)
    }
    else {
        return(plant_output_kg_per_year)
    }
}
get_h2_sales_kg_per_year <- function(operation_range, plant_output_kg_per_year, percnt_revs, start_time) {
    #'H2 sales (kg/year)
    return(mapply(function(year) list(calculate_h2_sales_kg_per_year(year, plant_output_kg_per_year, percnt_revs, start_time)), operation_range) )
}
