#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", YEAR_1, YEAR_2, YEAR_3, YEAR_4, .directory = here(h2a))
calculate_initial_equity_depr_cap <- function(year, inflation_price_increase_factor, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4) {
    #'In this model, the first 1 to 4 years are for construction. This function handles those years. The `year` arg begins at 0 and is incremented by 1 for each year.
    if (year == YEAR_1) {
        return(-inflation_price_increase_factor * percentage_equity_financing * depr_cap_infl * percent_cap1)
    }
    else if (year == YEAR_2) {
        return(-inflation_price_increase_factor * percentage_equity_financing * depr_cap_infl * percent_cap2)
    }
    else if (year == YEAR_3) {
        return(-inflation_price_increase_factor * percentage_equity_financing * depr_cap_infl * percent_cap3)
    }
    else if (year == YEAR_4) {
        return(-inflation_price_increase_factor * percentage_equity_financing * depr_cap_infl * percent_cap4)
    }
    else {
        return(0)
    }
}
get_initial_equity_depr_cap <- function(analysis_index_range, inflation_price_increase_factors, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4) {
    #'Initial Equity Depreciable Capital
    return(lapply(analysis_index_range, inflation_price_increase_factors, function(year, inflation_price_increase_factor) calculate_initial_equity_depr_cap(year, inflation_price_increase_factor, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4)))
}
