#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(get, get_cell, to_num, .from = "helpers.R", .directory = here("h2a"))
import::here(chemical_price_index, non_energy_material_prices, .from = "ref_tables.R", .directory = here("h2a"))
get_nonenergy_material_price_conversion_factor <- function(nonenergy_material, ref_year) {
    #'Get the conversion factor for converting Non-Energy Material prices from source year to reference year dollars
    return(get(chemical_price_index, ref_year) / get( chemical_price_index, get_cell(non_energy_material_prices, get(nonenergy_material, 'name'), 'Source Data Year') ))
}
get_nonenergy_material_price_for_year <- function(year, nonenergy_material, INFLATION_FACTOR, ref_year) {
    #'Calculate the price of a given Non-Energy Material for a year (although year is not used in this function)
    return(INFLATION_FACTOR * to_num(get(nonenergy_material, 'usage')) * ( get_cell(non_energy_material_prices, get(nonenergy_material, 'name'), 'Price') * get_nonenergy_material_price_conversion_factor(nonenergy_material, ref_year) ))
}
prices_for_nonenergy_material <- function(nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year) {
    #'Get prices for a given Non-Energy Material over a range of years
    return(mapply(function(year) list(get_nonenergy_material_price_for_year(year, nonenergy_material, INFLATION_FACTOR, ref_year)), analysis_range) )
}
get_nonenergy_material_price_df <- function(nonenergy_materials, analysis_range, INFLATION_FACTOR, ref_year) {
    #'Get a dataframe of Non-Energy Material prices over a range of years
    return(mapply(function(nonenergy_material) list(prices_for_nonenergy_material(nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year)), nonenergy_materials) )
}
