#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(get, .from = "helpers.R", .directory = here("h2a"))
import::here(chemical_price_index, non_energy_material_prices, .from = "ref_tables.R", .directory = here("h2a"))
get_nonenergy_material_price_conversion_factor <- function(nonenergy_material, ref_year) {
    #'Get the conversion factor for converting Non-Energy Material prices from source year to reference year dollars
    return(get(chemical_price_index, ref_year) / get( chemical_price_index, get( get(non_energy_material_prices, 'Source Data Year'), get(nonenergy_material, 'name') ) ))
}
get_nonenergy_material_price_for_year <- function(year, nonenergy_material, INFLATION_FACTOR, ref_year) {
    #'Calculate the price of a given Non-Energy Material for a year (although year is not used in this function)
    return(INFLATION_FACTOR * get(nonenergy_material, 'usage') * ( get( get(non_energy_material_prices, 'Price'), get(nonenergy_material, 'name'), ) * get_nonenergy_material_price_conversion_factor(nonenergy_material, ref_year) ))
}
prices_for_nonenergy_material <- function(nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year) {
    #'Get prices for a given Non-Energy Material over a range of years
    return(lapply(analysis_range, function(year) get_nonenergy_material_price_for_year(year, nonenergy_material, INFLATION_FACTOR, ref_year)))
}
get_nonenergy_material_price_df <- function(nonenergy_materials, analysis_range, INFLATION_FACTOR, ref_year) {
    #'Get a dataframe of Non-Energy Material prices over a range of years
    return(lapply(nonenergy_materials, function(nonenergy_material) prices_for_nonenergy_material(nonenergy_material, analysis_range, INFLATION_FACTOR, ref_year)))
}
