#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(YEAR_1, .from = "helpers.R", .directory = here("h2a"))
calculate_other_non_depr_cap <- function(year, inflation_price_increase_factor, non_dep_infl) {
    if (year == YEAR_1) {
        return(-inflation_price_increase_factor * non_dep_infl)
    }
    else {
        return(0)
    }
}
get_other_non_depreciable_capital_cost_column <- function(analysis_index_range, inflation_price_increase_factors, non_dep_infl) {
    #'Other Non-Depreciable Capital Costs
    return(mapply(function(year, inflation_price_increase_factor) list(calculate_other_non_depr_cap(year, inflation_price_increase_factor, non_dep_infl)), analysis_index_range, inflation_price_increase_factors) )
}
