#
# This file is programmatically generated by py_writer.py; do not edit
#
calculate_other_raw_material_cost <- function(year, inflation_price_increase_factor, inflated_otherraw, percnt_var, start_time) {
    if (year < 0) {
        return(0)
    }
    else if (year == 1 && start_time < 1) {
        return(-(( inflated_otherraw * inflation_price_increase_factor * percnt_var * start_time) + ( inflated_otherraw * inflation_price_increase_factor * (1 - start_time) )))
    }
    else if (year <= start_time) {
        return(-(inflated_otherraw * percnt_var * inflation_price_increase_factor))
    }
    else {
        return(-(inflated_otherraw * inflation_price_increase_factor))
    }
}
get_other_raw_material_cost_column <- function(operation_range, inflation_price_increase_factors, inflated_otherraw, percnt_var, start_time) {
    #'Other Raw Material Cost
    return(mapply(function(year, inflation_price_increase_factor) list(calculate_other_raw_material_cost(year, inflation_price_increase_factor, inflated_otherraw, percnt_var, start_time)), operation_range, inflation_price_increase_factors) )
}
