#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(filter_list, get, .from = "helpers.R", .directory = here("h2a"))
select_feedstock_from_list <- function(feedstock, term) {
    #'Determine if the feedstock is a match or not
    if (get(feedstock, 'name') == term) {
        return(TRUE)
    }
    else {
        return(FALSE)
    }
}
pick_feedstock <- function(feedstocks, term) {
    #'Given a list of feedstocks, return the one with the matching name
    return(filter_list(select_feedstock_from_list, feedstocks, term))
}
