#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(FIRST, SECOND, THIRD, concat, get, get_cell, split, to_num, .from = "helpers.R", .directory = here("h2a"))
import::here(co2_emission_factors, conversion_factor, .from = "ref_tables.R", .directory = here("h2a"))
calculate_ghg_emission_for_feedstock_and_ghg_column <- function(column_name, feedstock) {
    #'Get the ghg emission for a feedstock
    return(get_cell(co2_emission_factors, get(feedstock, 'name'), column_name) * to_num(get(feedstock, 'usage')) * conversion_factor(concat(get(split(get(feedstock, 'units'),'/'), FIRST), '_to_$/GJ')))
}
iterate_over_ghg_columns_for_feedstock <- function(feedstock, greenhouse_gas_column_names) {
    #'Iterate over the ghg columns for a feedstock
    return(mapply(function(column_name) list(calculate_ghg_emission_for_feedstock_and_ghg_column(column_name, feedstock)), greenhouse_gas_column_names) )
}
get_production_process_ghg_emissions_for_feedstocks <- function(feedstocks, greenhouse_gas_column_names) {
    #'Get production process GHG emissions for feedstocks
    return(mapply(function(feedstock) list(iterate_over_ghg_columns_for_feedstock(feedstock, greenhouse_gas_column_names)), feedstocks) )
}
calculate_total_ghg_emission_for_feedstock <- function(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get the ghg emission for a feedstock
    return(get(emission, FIRST) * GHG_CO2_factor + get(emission, SECOND) * GHG_CH4_factor + get(emission, THIRD) * GHG_N2O_factor)
}
get_production_process_total_ghg_emissions_for_feedstocks <- function(production_process_ghg_emissions_kg_per_kg_h2, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get production process total GHG emissions for feedstocks
    return(mapply(function(emission) list(calculate_total_ghg_emission_for_feedstock(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor)), production_process_ghg_emissions_kg_per_kg_h2) )
}
