#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", FIRST, SECOND, THIRD, concat, get, split, .directory = here(h2a))
import::from("ref_tables.R", co2_emission_factors, conversion_factor, .directory = here(h2a))
calculate_ghg_emission_for_feedstock_and_ghg_column <- function(column_name, feedstock) {
    #'Get the ghg emission for a feedstock
    return(get(get(co2_emission_factors, column_name), get(feedstock, 'name')) * get(feedstock, 'usage') * conversion_factor(concat(get(split(get(feedstock, 'units'),'/'), 0), '_to_$/GJ')))
}
iterate_over_ghg_columns_for_feedstock <- function(feedstock, greenhouse_gas_column_names) {
    #'Iterate over the ghg columns for a feedstock
    return(lapply(greenhouse_gas_column_names, function(column_name) calculate_ghg_emission_for_feedstock_and_ghg_column(column_name, feedstock)))
}
get_production_process_ghg_emissions_for_feedstocks <- function(feedstocks, greenhouse_gas_column_names) {
    #'Get production process GHG emissions for feedstocks
    return(lapply(feedstocks, function(feedstock) iterate_over_ghg_columns_for_feedstock(feedstock, greenhouse_gas_column_names)))
}
calculate_total_ghg_emission_for_feedstock <- function(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get the ghg emission for a feedstock
    return(get(emission, FIRST) * GHG_CO2_factor + get(emission, SECOND) * GHG_CH4_factor + get(emission, THIRD) * GHG_N2O_factor)
}
get_production_process_total_ghg_emissions_for_feedstocks <- function(production_process_ghg_emissions_kg_per_kg_h2, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get production process total GHG emissions for feedstocks
    return(lapply(production_process_ghg_emissions_kg_per_kg_h2, function(emission) calculate_total_ghg_emission_for_feedstock(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor)))
}
