#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", round_num, .directory = here(h2a))
convert_to_metric_tons_per_year <- function(emission, plant_output_kg_per_year) {
    #'Converts a value in kg per kg H2 to metric tons per year
    return(round_num(emission * plant_output_kg_per_year / 1000, -2))
}
get_total_in_metric_tons_per_year <- function(total_process_pollutants_produced_kg_per_kg_h2, plant_output_kg_per_year) {
    #'Convert total emissions for each GHG to metric tons per year
    return(lapply(total_process_pollutants_produced_kg_per_kg_h2, function(emission) convert_to_metric_tons_per_year(emission, plant_output_kg_per_year)))
}
