#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", evaluate, get, to_str, .directory = here(h2a))
calculate_replacement_cost <- function(year, inflation_price_increase_factor, replacement_costs_for_years, replace_factor, depr_cap, ref_year, startup_year, inflation_rate) {
    if (year < 0) {
        return(0)
    }
    else {
        return(-inflation_price_increase_factor * (evaluate(to_str(get(replacement_costs_for_years, year, 0))) + (replace_factor * depr_cap)) * ((1 + inflation_rate) ** (startup_year - ref_year)))
    }
}
get_replacement_costs <- function(operation_range, inflation_price_increase_factors, replacement_costs_for_years, replace_factor, depr_cap, ref_year, startup_year, inflation_rate) {
    #'Unplanned Yearly Replacement Capital (Depreciable)
    return(lapply(operation_range, inflation_price_increase_factors, function(year, inflation_price_increase_factor) calculate_replacement_cost(year, inflation_price_increase_factor, replacement_costs_for_years, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)))
}
