#
# This file is programmatically generated by py_writer.py; do not edit
#
calculate_replacement_cost <- function(year, inflation_price_increase_factor, replace_factor, depr_cap, ref_year, startup_year, inflation_rate) {
    if (year < 0) {
        return(0)
    }
    else {
        return(inflation_price_increase_factor * (replace_factor * depr_cap) * ((1 + inflation_rate) ** (startup_year - ref_year)))
    }
}
get_replacement_costs <- function(operation_range, inflation_price_increase_factors, replace_factor, depr_cap, ref_year, startup_year, inflation_rate) {
    #'Unplanned Yearly Replacement Capital (Depreciable)
    return(lapply(operation_range, inflation_price_increase_factors, function(year, inflation_price_increase_factor) calculate_replacement_cost(year, inflation_price_increase_factor, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)))
}
