#
# This file is programmatically generated by py_writer.py; do not edit
#

calculate_salvage_value <- function(year, inflation_price_increase_factor, salvage, plant_life) {
    if (year == plant_life) {
        return(inflation_price_increase_factor * salvage)
    }
    else {
        return(0)
    }
}
get_salvage_column <- function(operation_range, inflation_price_increase_factors, salvage, plant_life) {
    #'Salvage Value column
    return(mapply(function(year, inflation_price_increase_factor) list(calculate_salvage_value(year, inflation_price_increase_factor, salvage, plant_life)), operation_range, inflation_price_increase_factors) )
}
