#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(sum_args, .from = "helpers.R", .directory = here("h2a"))
get_taxable_income_column <- function(predepreciation_income_column, depreciation_charges_column) {
    #'Get the Taxable Income (Column V)
    return(mapply(function(predepreciation_income, depreciation_charges) list(sum_args(predepreciation_income, depreciation_charges)), predepreciation_income_column, depreciation_charges_column) )
}
