#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", sum_args, .directory = here(h2a))
get_taxable_income_column <- function(predepreciation_income_column, depreciation_charges_column) {
    #'Get the Taxable Income (Column V)
    return(lapply(predepreciation_income_column, depreciation_charges_column, function(predepreciation_income, depreciation_charges) sum_args(predepreciation_income, depreciation_charges)))
}
