#
# This file is programmatically generated by py_writer.py; do not edit
#
calculate_total_taxes <- function(taxable_income, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear) {
    #'Calculate the total taxes for a given taxable income
    return(tax_credit - (taxable_income * total_tax_rate + Upstream_CO2_taxpYear + Proc_CO2_taxpYear))
}
get_total_taxes_column <- function(taxable_income_column, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear) {
    #'Get the total taxes column (Column X)
    return(mapply(function(taxable_income) list(calculate_total_taxes(taxable_income, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear)), taxable_income_column) )
}
