#
# This file is programmatically generated by py_writer.py; do not edit
#
import::here(FIRST, SECOND, THIRD, get, get_cell, .from = "helpers.R", .directory = here("h2a"))
import::here(upstream_energy_and_emissions, .from = "ref_tables.R", .directory = here("h2a"))
calculate_ghg_emission_for_feedstock_and_ghg_column <- function(column_name, feedstock, energy_input) {
    #'Get the ghg emission for a feedstock
    return(energy_input * get_cell(upstream_energy_and_emissions, get(feedstock, 'name'), column_name))
}
iterate_over_ghg_columns_for_feedstock <- function(feedstock, energy_input, greenhouse_gas_column_names) {
    #'Iterate over the ghg columns for a feedstock
    return(mapply(function(column_name) list(calculate_ghg_emission_for_feedstock_and_ghg_column(column_name, feedstock, energy_input)), greenhouse_gas_column_names) )
}
get_upstream_ghg_emissions_for_feedstocks <- function(feedstocks, energy_input_GJ_per_kg_h2, greenhouse_gas_column_names) {
    #'Get upstream GHG emissions for feedstocks
    return(mapply(function(feedstock, energy_input) list(iterate_over_ghg_columns_for_feedstock(feedstock, energy_input, greenhouse_gas_column_names)), feedstocks, energy_input_GJ_per_kg_h2) )
}
calculate_total_ghg_emission <- function(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get the total ghg emission
    return(get(emission, FIRST) * GHG_CO2_factor + get(emission, SECOND) * GHG_CH4_factor + get(emission, THIRD) * GHG_N2O_factor)
}
get_total_ghg_emissions <- function(ghg_emissions_kg_per_kg_h2, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor) {
    #'Get upstream total GHG emissions
    return(mapply(function(emission) list(calculate_total_ghg_emission(emission, GHG_CO2_factor, GHG_CH4_factor, GHG_N2O_factor)), ghg_emissions_kg_per_kg_h2) )
}
