#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("helpers.R", get, .directory = here(h2a))
calculate_variable_cost_for_year <- function(year, price, inflation_price_increase_factor, plant_output_kg_per_year, percnt_var, start_time, inflated_othervar) {
    #'Calculate the variable cost for a given year
    if (year < 0) {
        return(0)
    }
    else if (year == 1 && start_time < 1) {
        return(-(( (price * plant_output_kg_per_year + inflated_othervar) * inflation_price_increase_factor * percnt_var * start_time ) + ( price * plant_output_kg_per_year * inflation_price_increase_factor * (1 - start_time) )))
    }
    else if (year <= start_time) {
        return(-(price * plant_output_kg_per_year + inflated_othervar) * inflation_price_increase_factor * percnt_var)
    }
    else {
        return(-(price * plant_output_kg_per_year + inflated_othervar) * inflation_price_increase_factor)
    }
}
material_prices_from_df <- function(nonenergy_material_price_df, i) {
    #'For a given year (i), return a list containing the price of each material
    return(lapply(nonenergy_material_price_df, function(material) get(material, i)))
}
get_variable_cost_column <- function(operation_range, analysis_index_range, nonenergy_material_price_df, inflation_price_increase_factors, plant_output_kg_per_year, percnt_var, start_time, inflated_othervar) {
    #'Other Variable Operating Costs column
    return(lapply(operation_range, analysis_index_range, inflation_price_increase_factors, function(year, i, inflation_price_increase_factor) calculate_variable_cost_for_year(year, sum(material_prices_from_df(nonenergy_material_price_df, i)), inflation_price_increase_factor, plant_output_kg_per_year, percnt_var, start_time, inflated_othervar)))
}
