#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("after_tax_income.R", get_after_tax_income_column, .directory = here(h2a,lib))
import::from("capital_investments.R", capital_investment_costs, .directory = here(h2a,lib))
import::from("cashflow.R", get_aftertax_post_depreciation_cashflow, get_cumulative_cashflow_column, get_pretax_cashflow_column, .directory = here(h2a,lib))
import::from("cashflow_meta.R", get_inflation_price_increase_factors, get_operation_range, .directory = here(h2a,lib))
import::from("debt_financing.R", determine_interest_payment, determine_principal_payment, .directory = here(h2a,lib))
import::from("decommissioning.R", get_decom_costs_column, .directory = here(h2a,lib))
import::from("depreciable_capital.R", get_annual_depreciable_capital, .directory = here(h2a,lib))
import::from("depreciation_calculation.R", get_depreciation_calculation_table, .directory = here(h2a,lib))
import::from("depreciation_charges.R", get_depreciation_charges, get_depreciation_charges_column, .directory = here(h2a,lib))
import::from("energy.R", get_energy_input_for_feedstocks, get_upstream_energy_usage_for_feedstocks, .directory = here(h2a,lib))
import::from("feedstock_costs.R", get_total_feedstock_costs, .directory = here(h2a,lib))
import::from("feedstock_prices.R", get_feedstock_price_df, .directory = here(h2a,lib))
import::from("fixed_costs.R", get_fixed_cost_column, .directory = here(h2a,lib))
import::from("h2_sales.R", get_h2_sales_kg_per_year, .directory = here(h2a,lib))
import::from("helpers.R", YEAR_1, args_to_list, evaluate, get, irr, npv, round_num, skip, slice, sum_args, sum_columns, .directory = here(h2a))
import::from("initial_equity.R", get_initial_equity_depr_cap, .directory = here(h2a,lib))
import::from("nonenergy_materials.R", get_nonenergy_material_price_df, .directory = here(h2a,lib))
import::from("other_non_depreciable_capital_cost.R", get_other_non_depreciable_capital_cost_column, .directory = here(h2a,lib))
import::from("other_raw_material_costs.R", get_other_raw_material_cost_column, .directory = here(h2a,lib))
import::from("predepreciation_income.R", get_predepreciation_income_column, .directory = here(h2a,lib))
import::from("production_process_ghg_emissions.R", get_production_process_ghg_emissions_for_feedstocks, get_production_process_total_ghg_emissions_for_feedstocks, .directory = here(h2a,lib))
import::from("production_process_ghg_emissions_summary.R", get_co2_captured_kg_per_kg_h2, get_co2_captured_metric_tons_per_year, get_total_in_metric_tons_per_year, get_total_process_emissions_kg_per_kg_h2, get_total_process_emissions_metric_tons_per_year, get_total_well_to_pump_emissions_kg_per_kg_h2, .directory = here(h2a,lib))
import::from("ref_tables.R", chemical_price_index, conversion_factor, conversion_factors, get_cpi, get_lhv, get_plant_cost_index, labor_index, macrs_depreciation_table, .directory = here(h2a))
import::from("replacement_costs.R", get_replacement_costs, .directory = here(h2a,lib))
import::from("revenue_h2_sales.R", get_revenue_h2_sales_column, .directory = here(h2a,lib))
import::from("salvage.R", get_salvage_column, .directory = here(h2a,lib))
import::from("taxable_income.R", get_taxable_income_column, .directory = here(h2a,lib))
import::from("total_taxes.R", get_total_taxes_column, .directory = here(h2a,lib))
import::from("upstream_ghg_emissions.R", calculate_total_ghg_emission, get_total_ghg_emissions, get_upstream_ghg_emissions_for_feedstocks, .directory = here(h2a,lib))
import::from("variable_costs.R", get_variable_cost_column, .directory = here(h2a,lib))
import::from("working_capital_reserve.R", get_working_cap_reserve_column, get_working_cap_reserve_rows, .directory = here(h2a,lib))

calculate <- function(user_input) {
  capacity_factor <- user_input[["capacity_factor"]]
  plant_design_capacity <- user_input[["plant_design_capacity"]]
  ref_year <- user_input[["ref_year"]]
  startup_year <- user_input[["startup_year"]]
  BasisYear <- user_input[["BasisYear"]]
  CurrentYear <- user_input[["CurrentYear"]]
  construct <- user_input[["construct"]]
  percent_cap1 <- user_input[["percent_cap1"]]
  percent_cap2 <- user_input[["percent_cap2"]]
  percent_cap3 <- user_input[["percent_cap3"]]
  percent_cap4 <- user_input[["percent_cap4"]]
  start_time <- user_input[["start_time"]]
  plant_life <- user_input[["plant_life"]]
  anal_period <- user_input[["anal_period"]]
  depr_length <- user_input[["depr_length"]]
  depr_type <- user_input[["depr_type"]]
  percentage_equity_financing <- user_input[["percentage_equity_financing"]]
  debt_interest <- user_input[["debt_interest"]]
  debt_period <- user_input[["debt_period"]]
  percnt_fixed <- user_input[["percnt_fixed"]]
  percnt_revs <- user_input[["percnt_revs"]]
  percnt_var <- user_input[["percnt_var"]]
  decom_percent <- user_input[["decom_percent"]]
  salvage_perct <- user_input[["salvage_perct"]]
  inflation_rate <- user_input[["inflation_rate"]]
  real_irr <- user_input[["real_irr"]]
  state_tax_rate <- user_input[["state_tax_rate"]]
  fed_tax_rate <- user_input[["fed_tax_rate"]]
  WorkingCap <- user_input[["WorkingCap"]]
  site_preparation <- user_input[["site_preparation"]]
  engineering_and_design <- user_input[["engineering_and_design"]]
  process_contingency <- user_input[["process_contingency"]]
  project_contingency <- user_input[["project_contingency"]]
  other_depreciable_capital_cost <- user_input[["other_depreciable_capital_cost"]]
  upfront_permitting <- user_input[["upfront_permitting"]]
  cost_per_acre <- user_input[["cost_per_acre"]]
  acres_required <- user_input[["acres_required"]]
  total_plant_staff <- user_input[["total_plant_staff"]]
  labor_cost_per_hour <- user_input[["labor_cost_per_hour"]]
  overhead_rate <- user_input[["overhead_rate"]]
  licensing <- user_input[["licensing"]]
  tax_ins_rate <- user_input[["tax_ins_rate"]]
  rent <- user_input[["rent"]]
  material_cost_maintenance_and_repairs <- user_input[["material_cost_maintenance_and_repairs"]]
  production_cost_maintenance_and_repairs <- user_input[["production_cost_maintenance_and_repairs"]]
  other_fees <- user_input[["other_fees"]]
  other_fixed <- user_input[["other_fixed"]]
  other_variable_operating_costs <- user_input[["other_variable_operating_costs"]]
  other_material_costs <- user_input[["other_material_costs"]]
  waste_treatment_costs <- user_input[["waste_treatment_costs"]]
  solid_waste_disposal_costs <- user_input[["solid_waste_disposal_costs"]]
  replace_factor <- user_input[["replace_factor"]]
  royalties <- user_input[["royalties"]]
  operator_profit <- user_input[["operator_profit"]]
  tax_credit_per_year <- user_input[["tax_credit_per_year"]]
  CO2_Capture_Efficiency <- user_input[["CO2_Capture_Efficiency"]]
  pipeline_length_km <- user_input[["pipeline_length_km"]]
  CO2_credit <- user_input[["CO2_credit"]]
  feedstocks <- user_input[["feedstocks"]]
  nonenergy_materials <- user_input[["nonenergy_materials"]]
  capital_investments <- user_input[["capital_investments"]]


  plant_output_kg_per_day <- plant_design_capacity * capacity_factor
  plant_output_kg_per_year <- plant_output_kg_per_day * 365
  full_analysis_period <- construct + anal_period
  analysis_period_start <- startup_year - construct
  analysis_period_end <- analysis_period_start + full_analysis_period
  CEPCIinflator <- get_plant_cost_index(CurrentYear) / get_plant_cost_index(BasisYear)
  CPIinflator <- get_cpi(ref_year) / get_cpi(CurrentYear)
  INFLATION_FACTOR <- (1 + inflation_rate) ** (startup_year - ref_year)
  H2_LHV_MJ_p_kg <- get_lhv("Hydrogen")
  output_energy_MMBtu_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg / 1000 / conversion_factor("mmBTU_to_GJ")
  output_energy_MJ_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg
  nominal_irr <- ((1 + real_irr) * (1 + inflation_rate)) - 1
  percentage_debt_financing <- 1 - percentage_equity_financing
  target_after_tax_nominal_irr <- (1 + real_irr)*(1 + inflation_rate) - 1
  analysis_range <- range(analysis_period_start, analysis_period_end)
  analysis_index_range <- seq_along(analysis_range)
  feedstock_price_df <- get_feedstock_price_df(feedstocks, analysis_range, startup_year, INFLATION_FACTOR)
  operation_range <- get_operation_range(analysis_index_range, construct)
  inflation_price_increase_factors <- get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year)
  total_feedstock_cost_column <- get_total_feedstock_costs(operation_range, feedstock_price_df, inflation_price_increase_factors, start_time, plant_output_kg_per_year, percnt_var)
  discounted_value_feedstock_cost <- get(total_feedstock_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(total_feedstock_cost_column, 1))
  direct_cap <- sum(capital_investment_costs(capital_investments, CEPCIinflator, CPIinflator))
  CO2_seq <- 0
  site_preparation_cost <- evaluate(site_preparation)
  engineering_and_design_cost <- evaluate(engineering_and_design)
  process_contingency_cost <- evaluate(process_contingency)
  project_contingency_cost <- evaluate(project_contingency)
  upfront_permitting_costs <- evaluate(upfront_permitting)
  depr_cap <- direct_cap + CO2_seq + (CEPCIinflator * CPIinflator) * (site_preparation_cost + engineering_and_design_cost + process_contingency_cost + project_contingency_cost + other_depreciable_capital_cost + upfront_permitting_costs)
  replacement_costs <- get_replacement_costs(operation_range, inflation_price_increase_factors, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)
  discounted_value_replacement_costs <- get(replacement_costs, YEAR_1) + npv(nominal_irr, skip(replacement_costs, 1))
  pv_of_cashflow_replacement_costs <- npv(nominal_irr, replacement_costs)
  land_cost <- acres_required * cost_per_acre * CPIinflator
  other_non_depreciable_capital_cost <- 0
  non_dep_cap <- land_cost + other_non_depreciable_capital_cost
  total_cap <- depr_cap + non_dep_cap
  depr_cap_infl <- (total_cap - non_dep_cap) * INFLATION_FACTOR
  non_dep_infl <- non_dep_cap * INFLATION_FACTOR
  total_capital_investment <- depr_cap_infl + non_dep_infl
  initial_equity_depr_cap <- get_initial_equity_depr_cap(analysis_index_range, inflation_price_increase_factors, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4)
  discounted_value_initial_equity_depr_cap <- get(initial_equity_depr_cap, YEAR_1) + npv(nominal_irr, skip(initial_equity_depr_cap, 1))
  pv_of_cashflow_initial_equity_depr_cap <- npv(nominal_irr, initial_equity_depr_cap)
  other_non_depreciable_capital_cost_column <- get_other_non_depreciable_capital_cost_column(analysis_index_range, inflation_price_increase_factors, non_dep_infl)
  discounted_value_other_non_depreciable_capital_cost <- get(other_non_depreciable_capital_cost_column, YEAR_1) + npv(nominal_irr, skip(other_non_depreciable_capital_cost_column, 1))
  pv_of_cashflow_other_non_depreciable_capital_cost <- npv(nominal_irr, other_non_depreciable_capital_cost_column)
  decom <- decom_percent * depr_cap_infl
  decom_costs_column <- get_decom_costs_column(operation_range, inflation_price_increase_factors, decom, plant_life)
  discounted_value_decom_costs <- get(decom_costs_column, YEAR_1) + npv(nominal_irr, skip(decom_costs_column, 1))
  salvage <- salvage_perct * total_capital_investment
  salvage_column <- get_salvage_column(operation_range, inflation_price_increase_factors, salvage, plant_life)
  FTE_HOURS_PER_YEAR <- 2080
  labor_cost_inflator <- get(labor_index, ref_year) / get(labor_index, BasisYear)
  labor_cost <- total_plant_staff * (labor_cost_per_hour * labor_cost_inflator) * FTE_HOURS_PER_YEAR
  overhead_GA <- labor_cost * overhead_rate
  tax_insurance <- tax_ins_rate * total_cap
  total_fixed_cost <- labor_cost + overhead_GA + tax_insurance + (CEPCIinflator*CPIinflator) * (licensing + rent + material_cost_maintenance_and_repairs + production_cost_maintenance_and_repairs + other_fees + other_fixed)
  inflated_fixed <- total_fixed_cost * INFLATION_FACTOR
  fixed_cost_column <- get_fixed_cost_column(operation_range, inflation_price_increase_factors, inflated_fixed, percnt_fixed, start_time)
  discounted_value_fixed_cost <- get(fixed_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(fixed_cost_column, 1))
  total_tax_rate <- fed_tax_rate + state_tax_rate * (1 - fed_tax_rate)
  percentage_debt_financing <- 1 - percentage_equity_financing
  initial_capital_financed <- -depr_cap_infl * percentage_debt_financing * get(inflation_price_increase_factors, YEAR_1)
  LAST_ANALYSIS_YEAR <- anal_period + construct - 1
  principal_payments_column <- determine_principal_payment(debt_period, analysis_index_range, LAST_ANALYSIS_YEAR, initial_capital_financed)
  interest_payments_column <- determine_interest_payment(debt_period, analysis_index_range, initial_capital_financed, debt_interest)
  discounted_value_interest_payments <- get(interest_payments_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(interest_payments_column, 1))
  pv_of_cashflow_interest_payments <- npv(nominal_irr, interest_payments_column)
  h2_sales_kg_per_year <- get_h2_sales_kg_per_year(operation_range, plant_output_kg_per_year, percnt_revs, start_time)
  discounted_value_total_h2_sales_kg <- get(h2_sales_kg_per_year, YEAR_1) + npv(real_irr, skip(h2_sales_kg_per_year, 1))
  LCOE_contribution_h2_sales_kg <- discounted_value_total_h2_sales_kg * (1 - total_tax_rate)
  discounted_value_total_salvage_value <- get(salvage_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(salvage_column, 1))
  pv_of_cashflow_total_salvage_value <- npv(nominal_irr, salvage_column)
  nonenergy_material_price_df <- get_nonenergy_material_price_df(nonenergy_materials, analysis_range, INFLATION_FACTOR, ref_year)
  var_misc <- other_variable_operating_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
  waste_treat <- waste_treatment_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
  solidwaste_treat <- solid_waste_disposal_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
  CO2_OandMcost <- 0
  inflated_othervar <- INFLATION_FACTOR * (var_misc + royalties + operator_profit + CO2_OandMcost + waste_treat + solidwaste_treat)
  variable_cost_column <- get_variable_cost_column(operation_range, analysis_index_range, nonenergy_material_price_df, inflation_price_increase_factors, plant_output_kg_per_year, percnt_var, start_time, inflated_othervar)
  discounted_value_variable_cost <- get(variable_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(variable_cost_column, 1))
  total_other_raw <- other_material_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
  inflated_otherraw <- total_other_raw * INFLATION_FACTOR
  other_raw_material_cost_column <- get_other_raw_material_cost_column(operation_range, inflation_price_increase_factors, inflated_otherraw, percnt_var, start_time)
  discounted_value_other_raw_material_cost <- get(other_raw_material_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(other_raw_material_cost_column, 1))
  working_cap_reserve_rows <- get_working_cap_reserve_rows(slice(operation_range, end = length(operation_range) - 1), slice(analysis_index_range, end = length(analysis_index_range) - 1), WorkingCap, fixed_cost_column, total_feedstock_cost_column, other_raw_material_cost_column, variable_cost_column)
  working_cap_reserve_column <- get_working_cap_reserve_column(working_cap_reserve_rows)
  discounted_value_working_cap_reserve <- get(working_cap_reserve_column, YEAR_1) + npv(nominal_irr, skip(working_cap_reserve_column, 1))
  pv_of_cashflow_working_cap_reserve <- npv(nominal_irr, working_cap_reserve_column)
  LCOE_contribution_capital_costs <- -(discounted_value_initial_equity_depr_cap + discounted_value_replacement_costs + discounted_value_working_cap_reserve + discounted_value_other_non_depreciable_capital_cost)
  total_initial_depreciable_capital <- -(initial_capital_financed + sum(initial_equity_depr_cap))
  annual_depreciable_capital <- get_annual_depreciable_capital(operation_range, replacement_costs, total_initial_depreciable_capital)
  recovery_range <- range(1, 22)
  depreciation_calculation_table <- get_depreciation_calculation_table(recovery_range, operation_range, depr_type, depr_length, annual_depreciable_capital)
  recovery_index_range <- seq_along(recovery_range)
  depreciation_charges <- get_depreciation_charges(analysis_index_range, recovery_index_range, depreciation_calculation_table)
  remaining_depreciation_range <- range(anal_period+construct, anal_period+construct+depr_length+1)
  remaining_depreciation_charges <- get_depreciation_charges(remaining_depreciation_range, recovery_index_range, depreciation_calculation_table)
  total_remaining_depreciation_charges <- sum(remaining_depreciation_charges)
  depreciation_charges_column <- get_depreciation_charges_column(depreciation_charges, analysis_index_range, total_remaining_depreciation_charges, anal_period, construct)
  discounted_value_depreciation_charges <- get(depreciation_charges_column, YEAR_1) + npv(nominal_irr, skip(depreciation_charges_column, 1))
  pv_of_cashflow_depreciation_charges <- npv(nominal_irr, depreciation_charges_column)
  LCOE_contribution_depreciation <- discounted_value_depreciation_charges * total_tax_rate
  LCOE_contribution_principal_payments <- -(get(principal_payments_column, YEAR_1) + npv(nominal_irr, skip(principal_payments_column, 1)))
  pv_of_cashflow_principal_payments <- npv(nominal_irr, principal_payments_column)
  LCOE_contribution_operation_costs <- -(discounted_value_total_salvage_value + discounted_value_decom_costs + discounted_value_fixed_cost + discounted_value_feedstock_cost + discounted_value_other_raw_material_cost + discounted_value_variable_cost + discounted_value_interest_payments) * (1-total_tax_rate)
  H2_price_nominal <- ((LCOE_contribution_capital_costs + LCOE_contribution_depreciation + LCOE_contribution_principal_payments + LCOE_contribution_operation_costs) / LCOE_contribution_h2_sales_kg) * (1 + inflation_rate) ** construct
  H2_price_real <- H2_price_nominal / INFLATION_FACTOR
  revenue_h2_sales <- get_revenue_h2_sales_column(operation_range, inflation_price_increase_factors, H2_price_nominal, plant_output_kg_per_year, percnt_revs, start_time)
  predepreciation_income_column <- get_predepreciation_income_column(revenue_h2_sales, salvage_column, decom_costs_column, fixed_cost_column, total_feedstock_cost_column, other_raw_material_cost_column, variable_cost_column, interest_payments_column)
  taxable_income_column <- get_taxable_income_column(predepreciation_income_column, depreciation_charges_column)
  tax_credit <- tax_credit_per_year * CPIinflator
  Upstream_CO2_taxpYear <- 0
  Proc_CO2_taxpYear <- 0
  total_taxes_column <- get_total_taxes_column(taxable_income_column, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear)
  after_tax_income_column <- get_after_tax_income_column(predepreciation_income_column, total_taxes_column)
  aftertax_post_depreciation_cashflow_column <- get_aftertax_post_depreciation_cashflow(initial_equity_depr_cap, replacement_costs, working_cap_reserve_column, other_non_depreciable_capital_cost_column, predepreciation_income_column, total_taxes_column, principal_payments_column)
  cumulative_cashflow_column <- get_cumulative_cashflow_column(aftertax_post_depreciation_cashflow_column, analysis_index_range)
  pretax_cashflow <- get_pretax_cashflow_column(initial_equity_depr_cap, replacement_costs, working_cap_reserve_column, other_non_depreciable_capital_cost_column, predepreciation_income_column, principal_payments_column)
  after_tax_nominal_IRR <- irr(aftertax_post_depreciation_cashflow_column)
  pre_tax_nominal_IRR <- irr(pretax_cashflow)
  aftertax_real_capital_recovery_factor <- (real_irr * (1 + real_irr) ** anal_period) / (((1 + real_irr) ** anal_period) - 1)
  aftertax_nominal_capital_recovery_factor <- (nominal_irr * (1 + nominal_irr) ** anal_period) / (((1 + nominal_irr) ** anal_period) - 1)
  total_real_fixed_charge_rate <- (aftertax_real_capital_recovery_factor * (1 - total_tax_rate * npv(real_irr, get(macrs_depreciation_table, depr_length))) ) / (1 - total_tax_rate)
  total_nominal_fixed_charge_rate <- (aftertax_nominal_capital_recovery_factor * (1 - total_tax_rate * npv(nominal_irr, get(macrs_depreciation_table, depr_length))) ) / (1 - total_tax_rate)
  after_tax_present_value_capital_related_costs <- (pv_of_cashflow_initial_equity_depr_cap + pv_of_cashflow_replacement_costs + pv_of_cashflow_working_cap_reserve + pv_of_cashflow_other_non_depreciable_capital_cost + (pv_of_cashflow_total_salvage_value * (1 - total_tax_rate)) + (pv_of_cashflow_interest_payments * (1 - total_tax_rate)) + (pv_of_cashflow_depreciation_charges * (-total_tax_rate)) + pv_of_cashflow_principal_payments) / (1 - total_tax_rate)
  after_tax_present_value_decommissioning_costs <- npv(nominal_irr, decom_costs_column)
  after_tax_present_value_fixed_cost <- npv(nominal_irr, fixed_cost_column)
  after_tax_present_value_total_feedstock_cost <- npv(nominal_irr, total_feedstock_cost_column)
  after_tax_present_value_other_raw_material_cost <- npv(nominal_irr, other_raw_material_cost_column)
  after_tax_present_value_byproduct_credits <- 0
  after_tax_present_value_variable_cost <- npv(nominal_irr, variable_cost_column)
  summed_cost_components <- sum_args(after_tax_present_value_capital_related_costs, after_tax_present_value_decommissioning_costs, after_tax_present_value_fixed_cost, after_tax_present_value_total_feedstock_cost, after_tax_present_value_other_raw_material_cost, after_tax_present_value_byproduct_credits, after_tax_present_value_variable_cost)
  percentage_of_cost_capital_related_costs <- after_tax_present_value_capital_related_costs / summed_cost_components
  percentage_of_cost_decommissioning_costs <- after_tax_present_value_decommissioning_costs / summed_cost_components
  percentage_of_cost_fixed_cost <- after_tax_present_value_fixed_cost / summed_cost_components
  percentage_of_cost_total_feedstock_cost <- after_tax_present_value_total_feedstock_cost / summed_cost_components
  percentage_of_cost_other_raw_material_cost <- after_tax_present_value_other_raw_material_cost / summed_cost_components
  percentage_of_cost_byproduct_credits <- after_tax_present_value_byproduct_credits / summed_cost_components
  percentage_of_cost_variable_cost <- after_tax_present_value_variable_cost / summed_cost_components
  dollars_per_kg_h2_capital_related_costs <- H2_price_real * percentage_of_cost_capital_related_costs
  dollars_per_kg_h2_decommissioning_costs <- H2_price_real * percentage_of_cost_decommissioning_costs
  dollars_per_kg_h2_fixed_cost <- H2_price_real * percentage_of_cost_fixed_cost
  dollars_per_kg_h2_total_feedstock_cost <- H2_price_real * percentage_of_cost_total_feedstock_cost
  dollars_per_kg_h2_other_raw_material_cost <- H2_price_real * percentage_of_cost_other_raw_material_cost
  dollars_per_kg_h2_byproduct_credits <- H2_price_real * percentage_of_cost_byproduct_credits
  dollars_per_kg_h2_variable_cost <- H2_price_real * percentage_of_cost_variable_cost
  energy_input_GJ_per_kg_h2 <- get_energy_input_for_feedstocks(feedstocks)
  production_process_energy_efficiency <- get(conversion_factors, 'kg_H2_LHV_to_GJ') / sum(energy_input_GJ_per_kg_h2)
  upstream_energy_usage_column_names <- args_to_list('Total Energy', 'Fossil Fuels', 'Petroleum')
  upstream_energy_usage_GJ_per_kg_h2 <- get_upstream_energy_usage_for_feedstocks(feedstocks, energy_input_GJ_per_kg_h2, upstream_energy_usage_column_names)
  greenhouse_gas_column_names <- args_to_list('CO2', 'CH4', 'N2O')
  upstream_ghg_emissions_kg_per_kg_h2 <- get_upstream_ghg_emissions_for_feedstocks(feedstocks, energy_input_GJ_per_kg_h2, greenhouse_gas_column_names)
  upstream_ghg_emissions_kg_per_kg_h2_total <- get_total_ghg_emissions(upstream_ghg_emissions_kg_per_kg_h2, get(conversion_factors, 'CO2'), get(conversion_factors, 'CH4'), get(conversion_factors, 'N2O'))
  production_process_ghg_emissions_kg_per_kg_h2 <- get_production_process_ghg_emissions_for_feedstocks(feedstocks, greenhouse_gas_column_names)
  production_process_ghg_emissions_kg_per_kg_h2_total <- get_production_process_total_ghg_emissions_for_feedstocks(production_process_ghg_emissions_kg_per_kg_h2, get(conversion_factors, 'CO2'), get(conversion_factors, 'CH4'), get(conversion_factors, 'N2O'))
  total_process_pollutants_produced_kg_per_kg_h2 <- sum_columns(production_process_ghg_emissions_kg_per_kg_h2)
  total_process_pollutants_produced_all_ghg_kg_per_kg_h2 <- sum(production_process_ghg_emissions_kg_per_kg_h2_total)
  total_process_pollutants_produced_metric_tons_per_year <- get_total_in_metric_tons_per_year(total_process_pollutants_produced_kg_per_kg_h2, plant_output_kg_per_year)
  total_process_pollutants_produced_all_ghg_metric_tons_per_year <- round_num(total_process_pollutants_produced_all_ghg_kg_per_kg_h2 * plant_output_kg_per_year / 1000, -2)
  total_feedstock_pollutants_produced_kg_per_kg_h2 <- sum_columns(production_process_ghg_emissions_kg_per_kg_h2)
  total_feedstock_pollutants_produced_all_ghg_kg_per_kg_h2 <- sum(production_process_ghg_emissions_kg_per_kg_h2_total)
  total_feedstock_pollutants_produced_metric_tons_per_year <- get_total_in_metric_tons_per_year(total_feedstock_pollutants_produced_kg_per_kg_h2, plant_output_kg_per_year)
  total_feedstock_pollutants_produced_all_ghg_metric_tons_per_year <- round_num(total_feedstock_pollutants_produced_all_ghg_kg_per_kg_h2 * plant_output_kg_per_year / 1000, -2)
  co2_captured_kg_per_kg_h2 <- get_co2_captured_kg_per_kg_h2(total_feedstock_pollutants_produced_kg_per_kg_h2, CO2_Capture_Efficiency)
  co2_captured_metric_tons_per_year <- get_co2_captured_metric_tons_per_year(co2_captured_kg_per_kg_h2, plant_output_kg_per_year)
  total_process_emissions_kg_per_kg_h2 <- get_total_process_emissions_kg_per_kg_h2(total_process_pollutants_produced_kg_per_kg_h2, co2_captured_kg_per_kg_h2)
  total_process_emissions_all_ghg_kg_per_kg_h2 <- calculate_total_ghg_emission(total_process_emissions_kg_per_kg_h2, get(conversion_factors, 'CO2'), get(conversion_factors, 'CH4'), get(conversion_factors, 'N2O'))
  total_process_emissions_metric_tons_per_year <- get_total_process_emissions_metric_tons_per_year(total_process_emissions_kg_per_kg_h2, plant_output_kg_per_year)
  total_upstream_emissions_kg_per_kg_h2 <- sum_columns(upstream_ghg_emissions_kg_per_kg_h2)
  total_upstream_emissions_all_ghg_kg_per_kg_h2 <- sum(upstream_ghg_emissions_kg_per_kg_h2_total)
  total_well_to_pump_emissions_kg_per_kg_h2 <- get_total_well_to_pump_emissions_kg_per_kg_h2(total_upstream_emissions_kg_per_kg_h2, total_process_emissions_kg_per_kg_h2)
  total_well_to_pump_emissions_all_ghg_kg_per_kg_h2 <- total_upstream_emissions_all_ghg_kg_per_kg_h2 + total_process_emissions_all_ghg_kg_per_kg_h2
  return(setNames(mget(ls()), ls()))
}
