#
# This file is programmatically generated by py_writer.py; do not edit
#
source(here("h2a", "inputs.R"))
import::from("capital_investments.R", capital_investment_costs, .directory = here(h2a, lib))
import::from("cashflow_meta.R", get_operation_range, get_inflation_price_increase_factors, .directory = here(h2a, lib))
import::from("decommissioning.R", get_decom_costs_column, .directory = here(h2a, lib))
import::from("feedstock_costs.R", get_total_feedstock_costs, .directory = here(h2a, lib))
import::from("feedstock_prices.R", get_feedstock_price_df, .directory = here(h2a, lib))
import::from("globals.R", plant_output_kg_per_year, analysis_period_start, analysis_period_end, INFLATION_FACTOR, CEPCIinflator, CPIinflator, .directory = here(h2a))
import::from("helpers.R", seq_along, .directory = here(h2a))
import::from("initial_equity.R", get_initial_equity_depr_cap, .directory = here(h2a, lib))
import::from("other_materials.R", get_other_material_price_df, .directory = here(h2a, lib))
import::from("other_non_depreciable_capital_cost.R", get_other_non_depreciable_capital_cost_column, .directory = here(h2a, lib))
import::from("ref_tables.R", get_lhv, conversion_factor, .directory = here(h2a))
import::from("replacement_costs.R", get_replacement_costs, .directory = here(h2a, lib))

H2_LHV_MJ_p_kg <- get_lhv("Hydrogen")
output_energy_MMBtu_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg / 1000 / conversion_factor("mmBTU_to_GJ")
output_energy_MJ_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg
nominal_irr <- ((1 + real_irr) * (1 + inflation_rate)) - 1
percentage_debt_financing <- 1 - percentage_equity_financing
target_after_tax_nominal_irr <- (1 + real_irr) * (1 + inflation_rate) - 1
analysis_range <- range(analysis_period_start, analysis_period_end)
analysis_index_range <- seq_along(analysis_range)
feedstock_price_df <- get_feedstock_price_df(feedstocks, analysis_range, startup_year)
operation_range <- get_operation_range(analysis_index_range, construct)
inflation_price_increase_factors <- get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year)
total_feedstock_cost_column <- get_total_feedstock_costs(operation_range, feedstock_price_df, inflation_price_increase_factors, start_time, plant_output_kg_per_year, percnt_var)
other_material_price_df <- get_other_material_price_df(other_materials, analysis_range, INFLATION_FACTOR, ref_year)
direct_cap <- sum(capital_investment_costs(capital_investments))
CO2_seq <- 0
site_preparation_cost <- (0.02 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.159872128446844 * direct_cap / (CEPCIinflator * CPIinflator))
engineering_and_design_cost <- (0.1 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
process_contingency_cost <- 0
project_contingency_cost <- 0.247793627342024 * direct_cap / (CEPCIinflator * CPIinflator)
other_depreciable_capital_cost <- 40137000
upfront_permitting_costs <- (0.15 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
depr_cap <- direct_cap + CO2_seq + (CEPCIinflator * CPIinflator) * (site_preparation_cost + engineering_and_design_cost + process_contingency_cost + project_contingency_cost + other_depreciable_capital_cost + upfront_permitting_costs)
replacement_costs <- get_replacement_costs(operation_range, inflation_price_increase_factors, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)
land_cost <- acres_required * cost_per_acre * CPIinflator
other_non_depreciable_capital_cost <- 0
non_dep_cap <- land_cost + other_non_depreciable_capital_cost
total_cap <- depr_cap + non_dep_cap
depr_cap_infl <- (total_cap - non_dep_cap) * INFLATION_FACTOR
non_dep_infl <- non_dep_cap * INFLATION_FACTOR
initial_equity_depr_cap <- get_initial_equity_depr_cap(analysis_index_range, inflation_price_increase_factors, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4)
other_non_depreciable_capital_cost_column <- get_other_non_depreciable_capital_cost_column(analysis_index_range, inflation_price_increase_factors, non_dep_infl)
decom <- decom_percent * depr_cap_infl
decom_costs_column <- get_decom_costs_column(operation_range, inflation_price_increase_factors, decom, plant_life)
