#
# This file is programmatically generated by py_writer.py; do not edit
#
import::from("inputs.R", BasisYear, CurrentYear, anal_period, capacity_factor, construct, inflation_rate, plant_design_capacity, ref_year, startup_year, .directory = here(h2a))
import::from("ref_tables.R", get_cpi, get_plant_cost_index, .directory = here(h2a))

plant_output_kg_per_day <- plant_design_capacity * capacity_factor
plant_output_kg_per_year <- plant_output_kg_per_day * 365
INFLATION_FACTOR <- (1 + inflation_rate) ** (startup_year - ref_year)
full_analysis_period <- construct + anal_period
analysis_period_start <- startup_year - construct
analysis_period_end <- analysis_period_start + full_analysis_period
CEPCIinflator <- get_plant_cost_index(CurrentYear) / get_plant_cost_index(BasisYear)
CPIinflator <- get_cpi(ref_year) / get_cpi(CurrentYear)
