#
# This file is programmatically generated by py_writer.py; do not edit
#
irr <- function(cfList) {
    return(tidyquant::IRR(cfList))
}

npv <- function(r, cfList) {
    sum_pv <- 0
    for (i in seq_along(cfList)) {
        sum_pv <- sum_pv + cfList[[i]] / ((1 + r) ^ i)
    }
    return(sum_pv)
}

round_num <- function(num, ndigits) {
    if (ndigits >= 0) {
        factor <- 10 ^ ndigits
        return(as.integer(num * factor + 0.5) / factor)
    } else {
        factor <- 10 ^ abs(ndigits)
        return(as.integer(num / factor + 0.5) * factor)
    }
}

to_str <- function(num) {
    return(as.character(num))
}

to_num <- function(str) {
    return(as.numeric(str))
}

get <- function(obj, key, default_val = 0) {
    if (is.null(obj[[key]])) {
        return(default_val)
    } else {
        return(obj[[key]])
    }
}

get_cell <- function(df, row, col) df[as.character(row), col]

concat <- function(a, b) paste(a, b, sep = "")

split <- function(a, b) strsplit(a, b)[[1]]

skip <- function(a, b) a[(b + 1):length(a)]

slice <- function(a, start=0, end=NULL) a[(start + 1):end]

sum_args <- function(...) sum(...)

sum_list <- function(a) sum(unlist(a))

num_range <- function(start, end) seq(start, end - 1)

sum_columns <- function(rows) {
    columns <- t(rows)
    df <- as.data.frame(do.call(rbind, columns))
    numeric_df <- dplyr::mutate_all(df, function(x) as.numeric(as.character(x)))
    return(colSums(numeric_df))
}

evaluate <- function(expr) eval(parse(text = expr))

args_to_list <- function(...) c(...)

YEAR_1 <- 1
YEAR_2 <- 2
YEAR_3 <- 3
YEAR_4 <- 4
FIRST <- 1
SECOND <- 2
THIRD <- 3
