#
# This file is programmatically generated by py_writer.py; do not edit
#
library(FinancialMath)

irr <- function(cfList) {
    return(IRR(cfList))
}

npv <- function(r, cfList) {
    sum_pv <- 0
    for (i in seq_along(cfList)) {
        sum_pv <- sum_pv + cfList[[i]] / ((1 + r) ^ i)
    }
    return(sum_pv)
}

round_num <- function(num, ndigits) {
    if (ndigits >= 0) {
        factor <- 10 ^ ndigits
        return(as.integer(num * factor + 0.5) / factor)
    } else {
        factor <- 10 ^ abs(ndigits)
        return(as.integer(num / factor + 0.5) * factor)
    }
}

to_str <- function(num) {
    return(as.character(num))
}

get <- function(obj, key, default_val = 0) {
    if (is.null(obj[[key]])) {
        return(default_val)
    } else {
        return(obj[[key]])
    }
}

concat <- function(a, b) paste(a, b, sep = "")

split <- function(a, b) strsplit(a, b)[[1]]

skip <- function(a, b) a[(b + 1):length(a)]

slice <- function(a, start=0, end=NULL) a[(start + 1):end]

sum_args <- function(...) sum(...)

sum_columns <- function(rows) {
    columns <- t(rows)
    return(apply(columns, 2, sum))
}

evaluate <- function(expr) eval(parse(text = expr))

args_to_list <- function(...) c(...)

YEAR_1 <- 1
YEAR_2 <- 2
YEAR_3 <- 3
YEAR_4 <- 4
FIRST <- 1
SECOND <- 2
THIRD <- 3
