#
# This file is programmatically generated by py_writer.py; do not edit
#
def get(obj, key):
    return obj[key]

def concat(a, b):
    return a + b

def split(a, b):
    return a.split(b)

def seq_along(a):
    return range(len(a))

TRUE = True