import os

# Get project root directory
root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Python Output Directory
py_dir = os.path.join(root_dir, "py")
py_h2a_dir = os.path.join(root_dir, "py", "h2a")

# R Output Directory
r_dir = os.path.join(root_dir, "R")
r_h2a_dir = os.path.join(root_dir, "R", "h2a")

# Whether to generate R files
R_ENABLED = True


INPUTS_FILENAME = "inputs"  # Python file containing the user input variables

code_writer_filename = "py_writer.py"  # Name of the file that writes the code
util_code = {
    "top_line_comment": {
        "py": f"""#
# This file is programmatically generated by {code_writer_filename}; do not edit
#
""",
        "R": f"""#
# This file is programmatically generated by {code_writer_filename}; do not edit
#
""",
    }
}
