#
# This file is programmatically generated by py_writer.py; do not edit
#
source(here('h2a', 'inputs.R'))
import::from("after_tax_income.R", get_after_tax_income_column, .directory = here(h2a,lib))
import::from("capital_investments.R", capital_investment_costs, .directory = here(h2a,lib))
import::from("cashflow.R", get_aftertax_post_depreciation_cashflow, get_cumulative_cashflow_column, get_pretax_cashflow_column, .directory = here(h2a,lib))
import::from("cashflow_meta.R", get_inflation_price_increase_factors, get_operation_range, .directory = here(h2a,lib))
import::from("debt_financing.R", determine_interest_payment, determine_principal_payment, .directory = here(h2a,lib))
import::from("decommissioning.R", get_decom_costs_column, .directory = here(h2a,lib))
import::from("depreciable_capital.R", get_annual_depreciable_capital, .directory = here(h2a,lib))
import::from("depreciation_calculation.R", get_depreciation_calculation_table, .directory = here(h2a,lib))
import::from("depreciation_charges.R", get_depreciation_charges, get_depreciation_charges_column, .directory = here(h2a,lib))
import::from("feedstock_costs.R", get_total_feedstock_costs, .directory = here(h2a,lib))
import::from("feedstock_prices.R", get_feedstock_price_df, .directory = here(h2a,lib))
import::from("fixed_costs.R", get_fixed_cost_column, .directory = here(h2a,lib))
import::from("globals.R", CEPCIinflator, CPIinflator, INFLATION_FACTOR, analysis_period_end, analysis_period_start, plant_output_kg_per_year, .directory = here(h2a))
import::from("h2_sales.R", get_h2_sales_kg_per_year, .directory = here(h2a,lib))
import::from("helpers.R", YEAR_1, get, irr, npv, skip, slice, .directory = here(h2a))
import::from("initial_equity.R", get_initial_equity_depr_cap, .directory = here(h2a,lib))
import::from("nonenergy_materials.R", get_nonenergy_material_price_df, .directory = here(h2a,lib))
import::from("other_non_depreciable_capital_cost.R", get_other_non_depreciable_capital_cost_column, .directory = here(h2a,lib))
import::from("other_raw_material_costs.R", get_other_raw_material_cost_column, .directory = here(h2a,lib))
import::from("predepreciation_income.R", get_predepreciation_income_column, .directory = here(h2a,lib))
import::from("ref_tables.R", chemical_price_index, conversion_factor, get_lhv, labor_index, macrs_depreciation_table, .directory = here(h2a))
import::from("replacement_costs.R", get_replacement_costs, .directory = here(h2a,lib))
import::from("revenue_h2_sales.R", get_revenue_h2_sales_column, .directory = here(h2a,lib))
import::from("salvage.R", get_salvage_column, .directory = here(h2a,lib))
import::from("taxable_income.R", get_taxable_income_column, .directory = here(h2a,lib))
import::from("total_taxes.R", get_total_taxes_column, .directory = here(h2a,lib))
import::from("variable_costs.R", get_variable_cost_column, .directory = here(h2a,lib))
import::from("working_capital_reserve.R", get_working_cap_reserve_column, get_working_cap_reserve_rows, .directory = here(h2a,lib))

H2_LHV_MJ_p_kg <- get_lhv("Hydrogen")
print(paste("H2_LHV_MJ_p_kg", H2_LHV_MJ_p_kg, sep = ": "))

output_energy_MMBtu_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg / 1000 / conversion_factor("mmBTU_to_GJ")
print(paste("output_energy_MMBtu_per_year", output_energy_MMBtu_per_year, sep = ": "))

output_energy_MJ_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg
print(paste("output_energy_MJ_per_year", output_energy_MJ_per_year, sep = ": "))

nominal_irr <- ((1 + real_irr) * (1 + inflation_rate)) - 1
print(paste("nominal_irr", nominal_irr, sep = ": "))

percentage_debt_financing <- 1 - percentage_equity_financing
print(paste("percentage_debt_financing", percentage_debt_financing, sep = ": "))

target_after_tax_nominal_irr <- (1 + real_irr)*(1 + inflation_rate) - 1
print(paste("target_after_tax_nominal_irr", target_after_tax_nominal_irr, sep = ": "))

analysis_range <- range(analysis_period_start, analysis_period_end)
print(paste("analysis_range", analysis_range, sep = ": "))

analysis_index_range <- seq_along(analysis_range)
print(paste("analysis_index_range", analysis_index_range, sep = ": "))

feedstock_price_df <- get_feedstock_price_df(feedstocks, analysis_range, startup_year)
print(paste("feedstock_price_df", feedstock_price_df, sep = ": "))

operation_range <- get_operation_range(analysis_index_range, construct)
print(paste("operation_range", operation_range, sep = ": "))

inflation_price_increase_factors <- get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year)
print(paste("inflation_price_increase_factors", inflation_price_increase_factors, sep = ": "))

total_feedstock_cost_column <- get_total_feedstock_costs(operation_range, feedstock_price_df, inflation_price_increase_factors, start_time, plant_output_kg_per_year, percnt_var)
print(paste("total_feedstock_cost_column", total_feedstock_cost_column, sep = ": "))

discounted_value_feedstock_cost <- get(total_feedstock_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(total_feedstock_cost_column, 1))
print(paste("discounted_value_feedstock_cost", discounted_value_feedstock_cost, sep = ": "))

direct_cap <- sum(capital_investment_costs(capital_investments))
print(paste("direct_cap", direct_cap, sep = ": "))

CO2_seq <- 0
print(paste("CO2_seq", CO2_seq, sep = ": "))

site_preparation_cost <- (0.02 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.159872128446844 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("site_preparation_cost", site_preparation_cost, sep = ": "))

engineering_and_design_cost <- (0.1 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("engineering_and_design_cost", engineering_and_design_cost, sep = ": "))

process_contingency_cost <- 0
print(paste("process_contingency_cost", process_contingency_cost, sep = ": "))

project_contingency_cost <- 0.247793627342024 * direct_cap / (CEPCIinflator * CPIinflator)
print(paste("project_contingency_cost", project_contingency_cost, sep = ": "))

other_depreciable_capital_cost <- 40137000
print(paste("other_depreciable_capital_cost", other_depreciable_capital_cost, sep = ": "))

upfront_permitting_costs <- (0.15 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("upfront_permitting_costs", upfront_permitting_costs, sep = ": "))

depr_cap <- direct_cap + CO2_seq + (CEPCIinflator * CPIinflator) * (site_preparation_cost + engineering_and_design_cost + process_contingency_cost + project_contingency_cost + other_depreciable_capital_cost + upfront_permitting_costs)
print(paste("depr_cap", depr_cap, sep = ": "))

replacement_costs <- get_replacement_costs(operation_range, inflation_price_increase_factors, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)
print(paste("replacement_costs", replacement_costs, sep = ": "))

discounted_value_replacement_costs <- get(replacement_costs, YEAR_1) + npv(nominal_irr, skip(replacement_costs, 1))
print(paste("discounted_value_replacement_costs", discounted_value_replacement_costs, sep = ": "))

land_cost <- acres_required * cost_per_acre * CPIinflator
print(paste("land_cost", land_cost, sep = ": "))

other_non_depreciable_capital_cost <- 0
print(paste("other_non_depreciable_capital_cost", other_non_depreciable_capital_cost, sep = ": "))

non_dep_cap <- land_cost + other_non_depreciable_capital_cost
print(paste("non_dep_cap", non_dep_cap, sep = ": "))

total_cap <- depr_cap + non_dep_cap
print(paste("total_cap", total_cap, sep = ": "))

depr_cap_infl <- (total_cap - non_dep_cap) * INFLATION_FACTOR
print(paste("depr_cap_infl", depr_cap_infl, sep = ": "))

non_dep_infl <- non_dep_cap * INFLATION_FACTOR
print(paste("non_dep_infl", non_dep_infl, sep = ": "))

total_capital_investment <- depr_cap_infl + non_dep_infl
print(paste("total_capital_investment", total_capital_investment, sep = ": "))

initial_equity_depr_cap <- get_initial_equity_depr_cap(analysis_index_range, inflation_price_increase_factors, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4)
print(paste("initial_equity_depr_cap", initial_equity_depr_cap, sep = ": "))

discounted_value_initial_equity_depr_cap <- get(initial_equity_depr_cap, YEAR_1) + npv(nominal_irr, skip(initial_equity_depr_cap, 1))
print(paste("discounted_value_initial_equity_depr_cap", discounted_value_initial_equity_depr_cap, sep = ": "))

other_non_depreciable_capital_cost_column <- get_other_non_depreciable_capital_cost_column(analysis_index_range, inflation_price_increase_factors, non_dep_infl)
print(paste("other_non_depreciable_capital_cost_column", other_non_depreciable_capital_cost_column, sep = ": "))

discounted_value_other_non_depreciable_capital_cost <- get(other_non_depreciable_capital_cost_column, YEAR_1) + npv(nominal_irr, skip(other_non_depreciable_capital_cost_column, 1))
print(paste("discounted_value_other_non_depreciable_capital_cost", discounted_value_other_non_depreciable_capital_cost, sep = ": "))

decom <- decom_percent * depr_cap_infl
print(paste("decom", decom, sep = ": "))

decom_costs_column <- get_decom_costs_column(operation_range, inflation_price_increase_factors, decom, plant_life)
print(paste("decom_costs_column", decom_costs_column, sep = ": "))

discounted_value_decom_costs <- get(decom_costs_column, YEAR_1) + npv(nominal_irr, skip(decom_costs_column, 1))
print(paste("discounted_value_decom_costs", discounted_value_decom_costs, sep = ": "))

salvage <- salvage_perct * total_capital_investment
print(paste("salvage", salvage, sep = ": "))

salvage_column <- get_salvage_column(operation_range, inflation_price_increase_factors, salvage, plant_life)
print(paste("salvage_column", salvage_column, sep = ": "))

FTE_HOURS_PER_YEAR <- 2080
print(paste("FTE_HOURS_PER_YEAR", FTE_HOURS_PER_YEAR, sep = ": "))

labor_cost_inflator <- get(labor_index, ref_year) / get(labor_index, BasisYear)
print(paste("labor_cost_inflator", labor_cost_inflator, sep = ": "))

labor_cost <- total_plant_staff * (labor_cost_per_hour * labor_cost_inflator) * FTE_HOURS_PER_YEAR
print(paste("labor_cost", labor_cost, sep = ": "))

overhead_GA <- labor_cost * overhead_rate
print(paste("overhead_GA", overhead_GA, sep = ": "))

tax_insurance <- tax_ins_rate * total_cap
print(paste("tax_insurance", tax_insurance, sep = ": "))

total_fixed_cost <- labor_cost + overhead_GA + tax_insurance + (CEPCIinflator*CPIinflator) * (licensing + rent + material_cost_maintenance_and_repairs + production_cost_maintenance_and_repairs + other_fees + other_fixed)
print(paste("total_fixed_cost", total_fixed_cost, sep = ": "))

inflated_fixed <- total_fixed_cost * INFLATION_FACTOR
print(paste("inflated_fixed", inflated_fixed, sep = ": "))

fixed_cost_column <- get_fixed_cost_column(operation_range, inflation_price_increase_factors, inflated_fixed, percnt_fixed, start_time)
print(paste("fixed_cost_column", fixed_cost_column, sep = ": "))

discounted_value_fixed_cost <- get(fixed_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(fixed_cost_column, 1))
print(paste("discounted_value_fixed_cost", discounted_value_fixed_cost, sep = ": "))

total_tax_rate <- fed_tax_rate + state_tax_rate * (1 - fed_tax_rate)
print(paste("total_tax_rate", total_tax_rate, sep = ": "))

percentage_debt_financing <- 1 - percentage_equity_financing
print(paste("percentage_debt_financing", percentage_debt_financing, sep = ": "))

initial_capital_financed <- -depr_cap_infl * percentage_debt_financing * get(inflation_price_increase_factors, YEAR_1)
print(paste("initial_capital_financed", initial_capital_financed, sep = ": "))

LAST_ANALYSIS_YEAR <- anal_period + construct - 1
print(paste("LAST_ANALYSIS_YEAR", LAST_ANALYSIS_YEAR, sep = ": "))

principal_payments_column <- determine_principal_payment(debt_period, analysis_index_range, LAST_ANALYSIS_YEAR, initial_capital_financed)
print(paste("principal_payments_column", principal_payments_column, sep = ": "))

interest_payments_column <- determine_interest_payment(debt_period, analysis_index_range, initial_capital_financed, debt_interest)
print(paste("interest_payments_column", interest_payments_column, sep = ": "))

discounted_value_interest_payments <- get(interest_payments_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(interest_payments_column, 1))
print(paste("discounted_value_interest_payments", discounted_value_interest_payments, sep = ": "))

h2_sales_kg_per_year <- get_h2_sales_kg_per_year(operation_range, plant_output_kg_per_year, percnt_revs, start_time)
print(paste("h2_sales_kg_per_year", h2_sales_kg_per_year, sep = ": "))

discounted_value_total_h2_sales_kg <- get(h2_sales_kg_per_year, YEAR_1) + npv(real_irr, skip(h2_sales_kg_per_year, 1))
print(paste("discounted_value_total_h2_sales_kg", discounted_value_total_h2_sales_kg, sep = ": "))

LCOE_contribution_h2_sales_kg <- discounted_value_total_h2_sales_kg * (1 - total_tax_rate)
print(paste("LCOE_contribution_h2_sales_kg", LCOE_contribution_h2_sales_kg, sep = ": "))

discounted_value_total_salvage_value <- get(salvage_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(salvage_column, 1))
print(paste("discounted_value_total_salvage_value", discounted_value_total_salvage_value, sep = ": "))

nonenergy_material_price_df <- get_nonenergy_material_price_df(nonenergy_materials, analysis_range, INFLATION_FACTOR, ref_year)
print(paste("nonenergy_material_price_df", nonenergy_material_price_df, sep = ": "))

var_misc <- other_variable_operating_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
print(paste("var_misc", var_misc, sep = ": "))

waste_treat <- waste_treatment_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
print(paste("waste_treat", waste_treat, sep = ": "))

solidwaste_treat <- solid_waste_disposal_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
print(paste("solidwaste_treat", solidwaste_treat, sep = ": "))

CO2_OandMcost <- 0
print(paste("CO2_OandMcost", CO2_OandMcost, sep = ": "))

inflated_othervar <- INFLATION_FACTOR * (var_misc + royalties + operator_profit + CO2_OandMcost + waste_treat + solidwaste_treat)
print(paste("inflated_othervar", inflated_othervar, sep = ": "))

variable_cost_column <- get_variable_cost_column(operation_range, analysis_index_range, nonenergy_material_price_df, inflation_price_increase_factors, plant_output_kg_per_year, percnt_var, start_time, inflated_othervar)
print(paste("variable_cost_column", variable_cost_column, sep = ": "))

discounted_value_variable_cost <- get(variable_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(variable_cost_column, 1))
print(paste("discounted_value_variable_cost", discounted_value_variable_cost, sep = ": "))

total_other_raw <- other_material_costs * get(chemical_price_index, ref_year) / get(chemical_price_index, BasisYear)
print(paste("total_other_raw", total_other_raw, sep = ": "))

inflated_otherraw <- total_other_raw * INFLATION_FACTOR
print(paste("inflated_otherraw", inflated_otherraw, sep = ": "))

other_raw_material_cost_column <- get_other_raw_material_cost_column(operation_range, inflation_price_increase_factors, inflated_otherraw, percnt_var, start_time)
print(paste("other_raw_material_cost_column", other_raw_material_cost_column, sep = ": "))

discounted_value_other_raw_material_cost <- get(other_raw_material_cost_column, YEAR_1) + npv(target_after_tax_nominal_irr, skip(other_raw_material_cost_column, 1))
print(paste("discounted_value_other_raw_material_cost", discounted_value_other_raw_material_cost, sep = ": "))

working_cap_reserve_rows <- get_working_cap_reserve_rows(slice(operation_range, end = length(operation_range) - 1), slice(analysis_index_range, end = length(analysis_index_range) - 1), WorkingCap, fixed_cost_column, total_feedstock_cost_column, other_raw_material_cost_column, variable_cost_column)
print(paste("working_cap_reserve_rows", working_cap_reserve_rows, sep = ": "))

working_cap_reserve_column <- get_working_cap_reserve_column(working_cap_reserve_rows)
print(paste("working_cap_reserve_column", working_cap_reserve_column, sep = ": "))

discounted_value_working_cap_reserve <- get(working_cap_reserve_column, YEAR_1) + npv(nominal_irr, skip(working_cap_reserve_column, 1))
print(paste("discounted_value_working_cap_reserve", discounted_value_working_cap_reserve, sep = ": "))

LCOE_contribution_capital_costs <- -(discounted_value_initial_equity_depr_cap + discounted_value_replacement_costs + discounted_value_working_cap_reserve + discounted_value_other_non_depreciable_capital_cost)
print(paste("LCOE_contribution_capital_costs", LCOE_contribution_capital_costs, sep = ": "))

total_initial_depreciable_capital <- -(initial_capital_financed + sum(initial_equity_depr_cap))
print(paste("total_initial_depreciable_capital", total_initial_depreciable_capital, sep = ": "))

annual_depreciable_capital <- get_annual_depreciable_capital(operation_range, replacement_costs, total_initial_depreciable_capital)
print(paste("annual_depreciable_capital", annual_depreciable_capital, sep = ": "))

recovery_range <- range(1, 22)
print(paste("recovery_range", recovery_range, sep = ": "))

depreciation_calculation_table <- get_depreciation_calculation_table(recovery_range, operation_range, depr_type, depr_length, annual_depreciable_capital)
print(paste("depreciation_calculation_table", depreciation_calculation_table, sep = ": "))

recovery_index_range <- seq_along(recovery_range)
print(paste("recovery_index_range", recovery_index_range, sep = ": "))

depreciation_charges <- get_depreciation_charges(analysis_index_range, recovery_index_range, depreciation_calculation_table)
print(paste("depreciation_charges", depreciation_charges, sep = ": "))

remaining_depreciation_range <- range(anal_period+construct, anal_period+construct+depr_length+1)
print(paste("remaining_depreciation_range", remaining_depreciation_range, sep = ": "))

remaining_depreciation_charges <- get_depreciation_charges(remaining_depreciation_range, recovery_index_range, depreciation_calculation_table)
print(paste("remaining_depreciation_charges", remaining_depreciation_charges, sep = ": "))

total_remaining_depreciation_charges <- sum(remaining_depreciation_charges)
print(paste("total_remaining_depreciation_charges", total_remaining_depreciation_charges, sep = ": "))

depreciation_charges_column <- get_depreciation_charges_column(depreciation_charges, analysis_index_range, total_remaining_depreciation_charges, anal_period, construct)
print(paste("depreciation_charges_column", depreciation_charges_column, sep = ": "))

discounted_value_depreciation_charges <- get(depreciation_charges_column, YEAR_1) + npv(nominal_irr, skip(depreciation_charges_column, 1))
print(paste("discounted_value_depreciation_charges", discounted_value_depreciation_charges, sep = ": "))

LCOE_contribution_depreciation <- discounted_value_depreciation_charges * total_tax_rate
print(paste("LCOE_contribution_depreciation", LCOE_contribution_depreciation, sep = ": "))

LCOE_contribution_principal_payments <- -(get(principal_payments_column, YEAR_1) + npv(nominal_irr, skip(principal_payments_column, 1)))
print(paste("LCOE_contribution_principal_payments", LCOE_contribution_principal_payments, sep = ": "))

LCOE_contribution_operation_costs <- -(discounted_value_total_salvage_value + discounted_value_decom_costs + discounted_value_fixed_cost + discounted_value_feedstock_cost + discounted_value_other_raw_material_cost + discounted_value_variable_cost + discounted_value_interest_payments) * (1-total_tax_rate)
print(paste("LCOE_contribution_operation_costs", LCOE_contribution_operation_costs, sep = ": "))

H2_price_nominal <- ((LCOE_contribution_capital_costs + LCOE_contribution_depreciation + LCOE_contribution_principal_payments + LCOE_contribution_operation_costs) / LCOE_contribution_h2_sales_kg) * (1 + inflation_rate) ** construct
print(paste("H2_price_nominal", H2_price_nominal, sep = ": "))

H2_price_real <- H2_price_nominal / INFLATION_FACTOR
print(paste("H2_price_real", H2_price_real, sep = ": "))

revenue_h2_sales <- get_revenue_h2_sales_column(operation_range, inflation_price_increase_factors, H2_price_nominal, plant_output_kg_per_year, percnt_revs, start_time)
print(paste("revenue_h2_sales", revenue_h2_sales, sep = ": "))

predepreciation_income_column <- get_predepreciation_income_column(revenue_h2_sales, salvage_column, decom_costs_column, fixed_cost_column, total_feedstock_cost_column, other_raw_material_cost_column, variable_cost_column, interest_payments_column)
print(paste("predepreciation_income_column", predepreciation_income_column, sep = ": "))

taxable_income_column <- get_taxable_income_column(predepreciation_income_column, depreciation_charges_column)
print(paste("taxable_income_column", taxable_income_column, sep = ": "))

tax_credit <- tax_credit_per_year * CPIinflator
print(paste("tax_credit", tax_credit, sep = ": "))

Upstream_CO2_taxpYear <- 0
print(paste("Upstream_CO2_taxpYear", Upstream_CO2_taxpYear, sep = ": "))

Proc_CO2_taxpYear <- 0
print(paste("Proc_CO2_taxpYear", Proc_CO2_taxpYear, sep = ": "))

total_taxes_column <- get_total_taxes_column(taxable_income_column, total_tax_rate, tax_credit, Upstream_CO2_taxpYear, Proc_CO2_taxpYear)
print(paste("total_taxes_column", total_taxes_column, sep = ": "))

after_tax_income_column <- get_after_tax_income_column(predepreciation_income_column, total_taxes_column)
print(paste("after_tax_income_column", after_tax_income_column, sep = ": "))

aftertax_post_depreciation_cashflow_column <- get_aftertax_post_depreciation_cashflow(initial_equity_depr_cap, replacement_costs, working_cap_reserve_column, other_non_depreciable_capital_cost_column, predepreciation_income_column, total_taxes_column, principal_payments_column)
print(paste("aftertax_post_depreciation_cashflow_column", aftertax_post_depreciation_cashflow_column, sep = ": "))

cumulative_cashflow_column <- get_cumulative_cashflow_column(aftertax_post_depreciation_cashflow_column, analysis_index_range)
print(paste("cumulative_cashflow_column", cumulative_cashflow_column, sep = ": "))

pretax_cashflow <- get_pretax_cashflow_column(initial_equity_depr_cap, replacement_costs, working_cap_reserve_column, other_non_depreciable_capital_cost_column, predepreciation_income_column, principal_payments_column)
print(paste("pretax_cashflow", pretax_cashflow, sep = ": "))

after_tax_nominal_IRR <- irr(aftertax_post_depreciation_cashflow_column)
print(paste("after_tax_nominal_IRR", after_tax_nominal_IRR, sep = ": "))

pre_tax_nominal_IRR <- irr(pretax_cashflow)
print(paste("pre_tax_nominal_IRR", pre_tax_nominal_IRR, sep = ": "))

aftertax_real_capital_recovery_factor <- (real_irr * (1 + real_irr) ** anal_period) / (((1 + real_irr) ** anal_period) - 1)
print(paste("aftertax_real_capital_recovery_factor", aftertax_real_capital_recovery_factor, sep = ": "))

aftertax_nominal_capital_recovery_factor <- (nominal_irr * (1 + nominal_irr) ** anal_period) / (((1 + nominal_irr) ** anal_period) - 1)
print(paste("aftertax_nominal_capital_recovery_factor", aftertax_nominal_capital_recovery_factor, sep = ": "))

total_real_fixed_charge_rate <- (aftertax_real_capital_recovery_factor * (1 - total_tax_rate * npv(real_irr, get(macrs_depreciation_table, depr_length))) ) / (1 - total_tax_rate)
print(paste("total_real_fixed_charge_rate", total_real_fixed_charge_rate, sep = ": "))

total_nominal_fixed_charge_rate <- (aftertax_nominal_capital_recovery_factor * (1 - total_tax_rate * npv(nominal_irr, get(macrs_depreciation_table, depr_length))) ) / (1 - total_tax_rate)
print(paste("total_nominal_fixed_charge_rate", total_nominal_fixed_charge_rate, sep = ": "))

