#
# This file is programmatically generated by py_writer.py; do not edit
#
source(here('h2a', 'inputs.R'))
import::from("capital_investments.R", capital_investment_costs, .directory = here(h2a,lib))
import::from("cashflow_meta.R", get_operation_range, get_inflation_price_increase_factors, .directory = here(h2a,lib))
import::from("decommissioning.R", get_decom_costs_column, .directory = here(h2a,lib))
import::from("feedstock_costs.R", get_total_feedstock_costs, .directory = here(h2a,lib))
import::from("feedstock_prices.R", get_feedstock_price_df, .directory = here(h2a,lib))
import::from("globals.R", plant_output_kg_per_year, analysis_period_start, analysis_period_end, INFLATION_FACTOR, CEPCIinflator, CPIinflator, .directory = here(h2a))
import::from("helpers.R", seq_along, .directory = here(h2a))
import::from("initial_equity.R", get_initial_equity_depr_cap, .directory = here(h2a,lib))
import::from("other_materials.R", get_other_material_price_df, .directory = here(h2a,lib))
import::from("other_non_depreciable_capital_cost.R", get_other_non_depreciable_capital_cost_column, .directory = here(h2a,lib))
import::from("ref_tables.R", get_lhv, conversion_factor, .directory = here(h2a))
import::from("replacement_costs.R", get_replacement_costs, .directory = here(h2a,lib))

H2_LHV_MJ_p_kg <- get_lhv("Hydrogen")
print(paste("H2_LHV_MJ_p_kg", H2_LHV_MJ_p_kg, sep = ": "))

output_energy_MMBtu_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg / 1000 / conversion_factor("mmBTU_to_GJ")
print(paste("output_energy_MMBtu_per_year", output_energy_MMBtu_per_year, sep = ": "))

output_energy_MJ_per_year <- plant_output_kg_per_year * H2_LHV_MJ_p_kg
print(paste("output_energy_MJ_per_year", output_energy_MJ_per_year, sep = ": "))

nominal_irr <- ((1 + real_irr) * (1 + inflation_rate)) - 1
print(paste("nominal_irr", nominal_irr, sep = ": "))

percentage_debt_financing <- 1 - percentage_equity_financing
print(paste("percentage_debt_financing", percentage_debt_financing, sep = ": "))

target_after_tax_nominal_irr <- (1 + real_irr)*(1 + inflation_rate) - 1
print(paste("target_after_tax_nominal_irr", target_after_tax_nominal_irr, sep = ": "))

analysis_range <- range(analysis_period_start, analysis_period_end)
print(paste("analysis_range", analysis_range, sep = ": "))

analysis_index_range <- seq_along(analysis_range)
print(paste("analysis_index_range", analysis_index_range, sep = ": "))

feedstock_price_df <- get_feedstock_price_df(feedstocks, analysis_range, startup_year)
print(paste("feedstock_price_df", feedstock_price_df, sep = ": "))

operation_range <- get_operation_range(analysis_index_range, construct)
print(paste("operation_range", operation_range, sep = ": "))

inflation_price_increase_factors <- get_inflation_price_increase_factors(analysis_range, inflation_rate, startup_year)
print(paste("inflation_price_increase_factors", inflation_price_increase_factors, sep = ": "))

total_feedstock_cost_column <- get_total_feedstock_costs(operation_range, feedstock_price_df, inflation_price_increase_factors, start_time, plant_output_kg_per_year, percnt_var)
print(paste("total_feedstock_cost_column", total_feedstock_cost_column, sep = ": "))

other_material_price_df <- get_other_material_price_df(other_materials, analysis_range, INFLATION_FACTOR, ref_year)
print(paste("other_material_price_df", other_material_price_df, sep = ": "))

direct_cap <- sum(capital_investment_costs(capital_investments))
print(paste("direct_cap", direct_cap, sep = ": "))

CO2_seq <- 0
print(paste("CO2_seq", CO2_seq, sep = ": "))

site_preparation_cost <- (0.02 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.159872128446844 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("site_preparation_cost", site_preparation_cost, sep = ": "))

engineering_and_design_cost <- (0.1 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("engineering_and_design_cost", engineering_and_design_cost, sep = ": "))

process_contingency_cost <- 0
print(paste("process_contingency_cost", process_contingency_cost, sep = ": "))

project_contingency_cost <- 0.247793627342024 * direct_cap / (CEPCIinflator * CPIinflator)
print(paste("project_contingency_cost", project_contingency_cost, sep = ": "))

other_depreciable_capital_cost <- 40137000
print(paste("other_depreciable_capital_cost", other_depreciable_capital_cost, sep = ": "))

upfront_permitting_costs <- (0.15 * CO2_seq / (CEPCIinflator * CPIinflator)) + (0.11599636520534 * direct_cap / (CEPCIinflator * CPIinflator))
print(paste("upfront_permitting_costs", upfront_permitting_costs, sep = ": "))

depr_cap <- direct_cap + CO2_seq + (CEPCIinflator * CPIinflator) * (site_preparation_cost + engineering_and_design_cost + process_contingency_cost + project_contingency_cost + other_depreciable_capital_cost + upfront_permitting_costs)
print(paste("depr_cap", depr_cap, sep = ": "))

replacement_costs <- get_replacement_costs(operation_range, inflation_price_increase_factors, replace_factor, depr_cap, ref_year, startup_year, inflation_rate)
print(paste("replacement_costs", replacement_costs, sep = ": "))

land_cost <- acres_required * cost_per_acre * CPIinflator
print(paste("land_cost", land_cost, sep = ": "))

other_non_depreciable_capital_cost <- 0
print(paste("other_non_depreciable_capital_cost", other_non_depreciable_capital_cost, sep = ": "))

non_dep_cap <- land_cost + other_non_depreciable_capital_cost
print(paste("non_dep_cap", non_dep_cap, sep = ": "))

total_cap <- depr_cap + non_dep_cap
print(paste("total_cap", total_cap, sep = ": "))

depr_cap_infl <- (total_cap - non_dep_cap) * INFLATION_FACTOR
print(paste("depr_cap_infl", depr_cap_infl, sep = ": "))

non_dep_infl <- non_dep_cap * INFLATION_FACTOR
print(paste("non_dep_infl", non_dep_infl, sep = ": "))

initial_equity_depr_cap <- get_initial_equity_depr_cap(analysis_index_range, inflation_price_increase_factors, depr_cap_infl, percentage_equity_financing, percent_cap1, percent_cap2, percent_cap3, percent_cap4)
print(paste("initial_equity_depr_cap", initial_equity_depr_cap, sep = ": "))

other_non_depreciable_capital_cost_column <- get_other_non_depreciable_capital_cost_column(analysis_index_range, inflation_price_increase_factors, non_dep_infl)
print(paste("other_non_depreciable_capital_cost_column", other_non_depreciable_capital_cost_column, sep = ": "))

decom <- decom_percent * depr_cap_infl
print(paste("decom", decom, sep = ": "))

decom_costs_column <- get_decom_costs_column(operation_range, inflation_price_increase_factors, decom, plant_life)
print(paste("decom_costs_column", decom_costs_column, sep = ": "))

